// ============================================================
// CLOUD PAINTS — Product Catalogue
// ============================================================
// Source-of-truth for the 18-product range. Copy, specs and
// claims transcribed from Cloudsent Decor Ltd. product labels
// (PDFs under Website Info and Media/). Industry-standard
// defaults fill gaps where products have no individual datasheet.
//
// Field contract used across the site:
//   slug, name, tagline, cat, cat_label, grade, kebs, brandClass,
//   primary, accent, image, sizes[], short, full,
//   features[]   — short bullet claims (label-verbatim)
//   specs{}      — quick-view grid (Coverage, Touch dry, Recoat,
//                  Hard dry, Finish, Thinning, Application, Cleaner)
//   uses[]       — real-world use cases
//   surfaces[]   — substrates the label lists
//   claims[]     — verbatim marketing lines (bigger callouts)
//   application{} — prep / new_surface / previously_painted / method
//   safety{}     — storage, first_aid, disposal, voc notes
//   datasheet    — relative path to the PDF for Download button
//   pairs_with[] — cross-sell slugs
// ============================================================

window.CLOUD_PRODUCTS = [

  /* ------------------------------------------------------------
     1. SILK VINYL 
     Label verbatim source: SILK VINYL 4LTS REV SEP.pdf
  ------------------------------------------------------------ */
  {
    slug: 'silk-vinyl',
    name: 'Silk Vinyl',
    tagline: 'Luxurious silky shades',
    cat: 'emulsion',
    cat_label: 'Interior Emulsion',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-silk-vinyl',
    primary: '#6b1f6e',
    accent: '#ec4899',
    image: 'images/buckets/SILK VINYL 4LTS REV SEP.jpg',
    sizes: ['1L', '4L', '20L'],
    short: 'High-quality interior water-based paint with a fashionable silky finish — built for offices, schools and hospitals where durability and beauty retention matter.',
    full: 'Cloud Paints Silk Wall Sheen is a high-quality interior water-based paint formulated using the latest technology of co-polymer with a fashionable Silky finish. Recommended for industrial offices, schools and hospitals for its durability and beauty retention.',
    features: [
      'Washable surface',
      'Resists fungus growth',
      'No harmful smell',
      'Luxurious silky sheen',
      'Water based · Lead free',
      'Interior use',
    ],
    specs: {
      'Coverage':   '10–12 m² per litre',
      'Touch dry':  '1 hour',
      'Recoat':     '3–4 hours',
      'Finish':     'Silky sheen',
      'Thinning':   '10–15% clean water (first coat only)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Clean water',
    },
    claims: ['Luxurious silky shades', 'Washable · Resists fungus growth'],
    uses: [
      'Interior offices and reception spaces',
      'Schools, hospitals and high-traffic institutional walls',
      'Living rooms, hallways and bedrooms where a silky finish is preferred',
    ],
    surfaces: ['Plaster', 'Concrete', 'Gypsum board', 'Previously painted interior walls'],
    application: {
      prep: 'Surfaces must first be thoroughly cleaned free from all dust and grease objects for a better result.',
      new_surface: 'Cloud Paints Undercoat is advisable to prime the surface before using the top coat of Cloud Paints Silk Vinyl Emulsion, and must be sanded properly for an absolute acceptable finish.',
      previously_painted: 'The surface must be sanded properly for an absolute acceptable finish before using the top coat of Cloud Paints Silk Vinyl Emulsion.',
      method: 'Stir well before use. Can be applied by brush, roller or spray equipment. For first coat on porous surfaces, ease of application and for spray application, paint can be thinned with 10–15% clean water. Avoid over-thinning.',
      cleanup: 'Clean equipment with clean water.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based · no harmful smell',
      storage: 'Store in a cool, dry place, out of direct sunlight. Keep lid tightly closed.',
      first_aid: 'In case of eye contact, rinse with plenty of clean water. If skin contact, wash with soap and water. Seek medical advice if irritation persists.',
      disposal: 'Do not empty into drains or watercourses. Dispose of in accordance with local regulations.',
    },
    datasheet: 'datasheets/silk-vinyl.pdf',
    pairs_with: ['supermatt', 'universal-undercoat', 'vinyl-matt'],
  },

  /* ------------------------------------------------------------
     2. VINYL MATT 
     Label verbatim source: VINYL MATT 4LTS REV SEP.pdf
  ------------------------------------------------------------ */
  {
    slug: 'vinyl-matt',
    name: 'Vinyl Matt',
    tagline: 'High-quality matt finish for interior & exterior',
    cat: 'emulsion',
    cat_label: 'Interior & Exterior Emulsion',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-vinyl-matt',
    primary: '#1e3a8a',
    accent: '#3b5bdb',
    image: 'images/buckets/VINYL MATT 4LTS REV SEP.jpg',
    sizes: ['1L', '4L', '20L'],
    short: 'Premium-grade acrylic-based emulsion with an attractive hard-wearing matt finish. Suitable for both interior and exterior surfaces and can be applied directly to plaster and wooden surfaces.',
    full: 'This is a premium grade Acrylic Base Emulsion with an attractive hard-wearing matt finish suitable for interior and also exterior surfaces. Cloud Paints Vinyl Matt can be directly used either in plaster and wooden surfaces as well.',
    features: [
      'High-quality hard-wearing matt finish',
      'Smooth flow for easy application',
      'Interior & exterior use',
      'No harmful smell',
      'Lead free · Water based',
      'Quick dry',
    ],
    specs: {
      'Coverage':   '10–12 m² per litre',
      'Touch dry':  '1 hour',
      'Recoat':     '3–4 hours',
      'Finish':     'Hard-wearing matt',
      'Thinning':   '10–15% clean water (first coat only)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Clean water',
    },
    claims: ['High quality finish', 'Smooth flow for easy application', 'For interior & exterior'],
    uses: [
      'Interior and exterior residential walls',
      'Commercial buildings needing a durable matt look',
      'Direct application to plaster and wooden surfaces',
    ],
    surfaces: ['Plaster', 'Concrete', 'Wood', 'Gypsum', 'Previously painted surfaces'],
    application: {
      prep: 'Surfaces must first be thoroughly cleaned free from all dust and grease objects for a better result.',
      new_surface: 'Cloud Paints Undercoat is advisable to prime the surface before using the top coat of Cloud Paints Vinyl Matt Emulsion and must be sanded properly for an absolute acceptable finish.',
      previously_painted: 'The surface must be sanded properly for an absolute acceptable finish before using the top coat of Cloud Paints Vinyl Matt Emulsion.',
      method: 'Stir well before use. Can be applied by brush, roller or spray equipment. For first coat on porous surfaces, ease of application and for spray application, paint can be thinned with 10–15% clean water. Avoid over-thinning.',
      cleanup: 'Clean equipment with clean water.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based · no harmful smell',
      storage: 'Store in a cool, dry place, out of direct sunlight. Keep lid tightly closed.',
      first_aid: 'In case of eye contact, rinse with plenty of clean water. If skin contact, wash with soap and water. Seek medical advice if irritation persists.',
      disposal: 'Do not empty into drains or watercourses. Dispose of in accordance with local regulations.',
    },
    datasheet: 'datasheets/vinyl-matt.pdf',
    pairs_with: ['weatherguard', 'supermatt', 'universal-undercoat'],
  },

  /* ------------------------------------------------------------
     3. IRIS PLASTIC EMULSION 
     Label verbatim source: IRISH REV 4L SEP.pdf
  ------------------------------------------------------------ */
  {
    slug: 'iris-economy',
    name: 'Iris Plastic Emulsion',
    tagline: 'Excellent opacity · Odourless · Eco-friendly',
    cat: 'emulsion',
    cat_label: 'Economy Emulsion',
    grade: 'Economy',
    kebs: '',
    brandClass: 'brand-iris',
    primary: '#d4940a',
    accent: '#fbbf24',
    image: 'images/buckets/IRISH REV 4L SEP.jpg',
    sizes: ['1L', '4L', '20L'],
    short: 'Acrylic co-polymer based economy emulsion with a smooth, flat decorative finish and good hiding power. Anti-fungal and anti-bacterial — recommended for interior walls and ceilings.',
    full: 'Cloud Paints Iris Plastic Emulsion is an acrylic co-polymer based quality economical emulsion paint with a smooth, flat and decorative finish with good hiding power. It contains anti-fungal and anti-bacterial additives. It is recommended for masonry application and decoration of interior surfaces like concrete, plaster, gypsum board, asbestos, walls and ceilings.',
    features: [
      'Excellent opacity',
      'Odourless · Eco-friendly',
      'Smooth flat decorative finish',
      'Anti-fungal & anti-bacterial additives',
      'Lead free · Water based',
      'Easy to apply',
    ],
    specs: {
      'Coverage':   '12 m² per litre',
      'Touch dry':  '1 hour',
      'Recoat':     '3–4 hours',
      'Finish':     'Smooth matt',
      'Thinning':   'Water as required (first coat)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Clean water',
    },
    claims: ['Excellent opacity', 'Odourless & eco-friendly', 'For interior walls & ceilings'],
    uses: [
      'Interior walls and ceilings',
      'Masonry decoration on concrete and plaster',
      'Cost-effective choice for high-coverage jobs',
    ],
    surfaces: ['Concrete', 'Plaster', 'Gypsum board', 'Asbestos', 'Walls', 'Ceilings'],
    application: {
      prep: 'Surfaces must first be thoroughly cleaned free from all dust and grease objects for a better result.',
      new_surface: 'Cloud Paints Iris Plastic Emulsion is advisable to prime the surface before using 1 coat of Cloud Paints Undercoat and must be sanded properly for an absolute acceptable finish.',
      previously_painted: 'The surface must be sanded properly for an absolute acceptable finish before using the top coat of Cloud Paints Iris Plastic Emulsion.',
      method: 'Stir well before use. Cloud Paints Iris Plastic Emulsion can be applied by brush, roller or spray equipment.',
      cleanup: 'Clean equipment with clean water.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based · odourless',
      storage: 'Store in a cool, dry place, out of direct sunlight. Keep lid tightly closed.',
      first_aid: 'In case of eye contact, rinse with plenty of clean water. If skin contact, wash with soap and water. Seek medical advice if irritation persists.',
      disposal: 'Do not empty into drains or watercourses. Dispose of in accordance with local regulations.',
    },
    datasheet: 'datasheets/iris-economy.pdf',
    pairs_with: ['supermatt', 'universal-undercoat'],
  },

  /* ------------------------------------------------------------
     4. SUPERMATT EMULSION 
     Label verbatim source: SUPERMATT REV 4L.pdf
  ------------------------------------------------------------ */
  {
    slug: 'supermatt',
    name: 'SuperMatt Emulsion',
    tagline: 'Excellent coverage & hiding power',
    cat: 'undercoat',
    cat_label: 'Emulsion Undercoat',
    grade: 'Trade',
    kebs: '',
    brandClass: 'brand-supermatt',
    primary: '#b8243a',
    accent: '#d92843',
    image: 'images/buckets/SUPERMATT REV 4L.jpg',
    sizes: ['1L', '4L', '20L'],
    short: 'Trade-quality water-based emulsion undercoat with excellent coverage, filling properties and a long-lasting bright matt finish. The smooth base for every decorative top coat.',
    full: 'Cloud Paints SuperMatt is a trade quality emulsion paint used for both interior and exterior. A water-based undercoat that has an excellent coverage, finish and application properties. It also provides a smooth base for the top coat application of all decorative products. Its high-quality filling properties has made it ideal for use on all types of interior, exterior and masonry surfaces. Cloud Paints SuperMatt is a high quality, acrylic-based paint, fast drying with a long lasting bright matt finish.',
    features: [
      'Excellent coverage & hiding power',
      'High-quality filling properties',
      'Fast drying',
      'Smooth base for topcoats',
      'Interior & exterior use',
      'Lead free · No harmful smell',
    ],
    specs: {
      'Coverage':   '10–12 m² per litre',
      'Touch dry':  '1 hour',
      'Recoat':     '2–3 hours',
      'Finish':     'Bright matt',
      'Thinning':   '≤25% water (do not exceed)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Water — rinse tools properly for next use',
    },
    claims: ['Excellent coverage & hiding power', 'Emulsion for ceilings & walls'],
    uses: [
      'Undercoat under Cloud Paints decorative top coats',
      'Economical finishing of ceilings and walls',
      'High-coverage interior, exterior and masonry surfaces',
    ],
    surfaces: ['Concrete', 'Plaster', 'Masonry', 'Gypsum', 'Previously painted surfaces'],
    application: {
      prep: 'Surfaces must first be thoroughly cleaned free from all dust and grease objects for a better result.',
      new_surface: 'It is advisable to prime the surface before using the top coat of Cloud Paints Silk Vinyl Emulsion and must be sanded properly for an absolute acceptable finish.',
      previously_painted: 'The surface must be sanded properly for an absolute acceptable finish before using the top coat of Cloud Paints Silk Vinyl Emulsion.',
      method: 'Stir well before use. Cloud Paints SuperMatt Undercoat can be applied by brush, roller or spray equipment. It should not be thinned beyond 25% of water. An interval of 2–3 hrs is recommended for re-coating and gives an absolute good result.',
      cleanup: 'Clean tools with water and rinse properly for the next use.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based · no harmful smell',
      storage: 'Store in a cool, dry place, out of direct sunlight. Keep lid tightly closed.',
      first_aid: 'In case of eye contact, rinse with plenty of clean water. If skin contact, wash with soap and water. Seek medical advice if irritation persists.',
      disposal: 'Do not empty into drains or watercourses. Dispose of in accordance with local regulations.',
    },
    datasheet: 'datasheets/supermatt.pdf',
    pairs_with: ['vinyl-matt', 'silk-vinyl', 'weatherguard'],
  },

  /* ------------------------------------------------------------
     5. WEATHERGUARD 
     Label verbatim source: WEATHERGUARD 4LTS REV SEP.pdf
  ------------------------------------------------------------ */
  {
    slug: 'weatherguard',
    name: 'Weatherguard',
    tagline: 'Tough · Durable · Ultimate weather resistance',
    cat: 'exterior',
    cat_label: 'Exterior Protection',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-weatherguard',
    primary: '#8b1e2c',
    accent: '#d92843',
    image: 'images/buckets/WEATHERGUARD 4LTS REV SEP.jpg',
    sizes: ['1L', '4L', '20L'],
    short: 'High-performance acrylic emulsion with silicone, fungicides and anti-carbonation formula. Built for humid tropical coastal conditions. Covers hairline cracks and hides minor imperfections.',
    full: 'Cloud Paints Weather Guard is a high performance Acrylic Emulsion paint containing special fungicides. It is formulated to give long term protection to Exterior and all kinds of exposed surfaces especially prone to mould and algae attack. Cloud Paints Weather Guard is ideally suited to areas of humidity and tropical coastal conditions.',
    features: [
      'Excellent resistance against dirt, chemicals and peeling',
      'Resists fungus and algae growth',
      'Anti-carbonation formula protects against fading of colours',
      'With silicone',
      'Covers hairline cracks & hides minor imperfections',
      'Quick dry · Washable',
    ],
    specs: {
      'Coverage':   '10–12 m² per litre',
      'Touch dry':  '1 hour',
      'Recoat':     '3–4 hours',
      'Finish':     'Smooth matt',
      'Thinning':   '10–15% clean water (first coat only)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Clean water',
    },
    claims: [
      'Tough, Durable, Ultimate Weather Resistance.',
      'Covers Hairline Cracks, Hides Minor Imperfections.',
      'With Silicone.',
    ],
    uses: [
      'Residential and commercial exterior walls',
      'Humid and coastal areas — Mombasa, Kilifi, Malindi, Diani',
      'Surfaces prone to mould and algae attack',
      'Concrete, plaster and masonry exteriors',
    ],
    surfaces: ['Concrete', 'Plaster', 'Masonry', 'Cement render', 'Previously painted exteriors'],
    application: {
      prep: 'Surfaces must first be thoroughly cleaned free from all dust and grease objects for a better result.',
      new_surface: 'Cloud Paints Weather Guard is advisable to prime the surface before using the top coat of Cloud Paints Weather Guard and must be sanded properly for an absolute acceptable finish.',
      previously_painted: 'The surface must be sanded properly for an absolute acceptable finish before using the top coat of Cloud Paints Weather Guard.',
      method: 'Stir well before use. Cloud Paints Weather Guard Emulsion can be applied by brush, roller or spray equipment. For first coat on porous surfaces, ease of application and for spray application, paint can be thinned with 10–15% clean water. Avoid over-thinning.',
      cleanup: 'Clean equipment with clean water.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based',
      storage: 'Store in a cool, dry place, out of direct sunlight. Keep lid tightly closed.',
      first_aid: 'In case of eye contact, rinse with plenty of clean water. If skin contact, wash with soap and water. Seek medical advice if irritation persists.',
      disposal: 'Do not empty into drains or watercourses. Dispose of in accordance with local regulations.',
    },
    datasheet: 'datasheets/weatherguard.pdf',
    pairs_with: ['rocketex', 'supermatt', 'roof-paint'],
  },

  /* ------------------------------------------------------------
     6. ROCKETEX (RockTEX / RuffTEX) 
     Label verbatim source: Cloudsent Paint Label - 2020 - RockTex - FINAL.pdf
  ------------------------------------------------------------ */
  {
    slug: 'rocketex',
    name: 'Rocketex Wallmaster',
    tagline: 'Polymer textured paint · Extra tough',
    cat: 'exterior',
    cat_label: 'Polymer Textured Coating',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-rocketex',
    primary: '#1f2547',
    accent: '#3b5bdb',
    image: 'images/buckets/ROCKETEX 30KG.jpg',
    sizes: ['5kg', '30kg'],
    short: 'Super-premium 100% acrylic textured coating. Trowel or roller applied for multi-directional textures and designer finishes. 15-year all-weather protection warranty. Over 5,000 colour shades.',
    full: 'Cloud RockTEX Texture is a super-premium Acrylic Emulsion based on an acrylic resin for a textured finish with guaranteed high performance, formulated to provide multi-directional textures (creation of designer texture and designs). It comes in more than 5,000 exuberant colours on any exterior & interior cementitious surface. A flexible acrylic texture applied directly from the bucket. Formulated with special materials such as tough stone crystals that give it unparalleled toughness and durability, making it a perfect choice for exterior painting and also interiors.',
    features: [
      'Stylish multiple textured effects',
      'Light rock finish',
      'Trowel or roller applied',
      'Excellent adhesion to wall',
      'Anti-carbonation formula',
      '15-year all-weather warranty',
    ],
    specs: {
      'Coverage':   '10–11 m² per 30 kg @ 1–1.5 mm film',
      'Touch dry':  '4 hours',
      'Hard dry':   '24 hours',
      'Max hardness': '7 days',
      'Finish':     'Matt high-build textured',
      'Thinning':   'Supplied ready-to-use — do not thin',
      'Application': 'Stainless-steel trowel · Roller',
      'Cleaner':    'Clean water',
    },
    claims: [
      'Strong & tuff.',
      'Stylish multiple textured effects.',
      '15-year all-weather protection warranty.',
      'Over 5,000 shades to choose from.',
    ],
    uses: [
      'Exterior feature walls and villas',
      'Interior accent walls with designer textures',
      'Hiding surface imperfections on older buildings',
      'Hospitality and commercial façades',
    ],
    surfaces: ['Plaster', 'Cement rendering', 'Block work', 'Cement', 'Stone', 'Bag-washed concrete', 'Fair-faced concrete', 'Timber', 'Glass', 'Aluminium'],
    application: {
      prep: 'All surfaces must be thoroughly cleaned and free of all dirt, loose and flaking paint. Efflorescence or mould must be treated before application. New concrete, mortar or cement render must be allowed to cure for 4 to 8 weeks depending on concrete thickness and drying conditions. Fill holes with grouting cement. Wash down with water using a stiff brush to remove all loose material.',
      new_surface: 'On porous surfaces, apply a priming coat thinned with water (4 parts RockTEX Texture : 1 part water) to condition the surface and aid application of additional coats.',
      previously_painted: 'Remove all loose and flaking paint. Clean thoroughly. Treat any efflorescence or mould before re-coating.',
      method: 'Apply using a stainless-steel trowel. For finishing and texturing, a special finishing tool (stainless-steel trowel, plastic trowel or comb) is required depending upon the textured finish (circular, horizontal, vertical). STIR THOROUGHLY BEFORE USE. Best applied when wet.',
      cleanup: 'Clean tools with water immediately after use.',
    },
    safety: {
      lead: 'No added lead, mercury or chromium compounds',
      voc: 'Water-based · low VOC',
      storage: 'Store container in upright position, with lid tightly closed, in a cool, dry place.',
      first_aid: 'Keep out of the reach of children and away from food, drink and animal feed. May be harmful if swallowed. In case of ingestion seek immediate medical attention.',
      disposal: 'Do not pour leftover paint down the drains or in water-courses. Contain spillage using sand or earth.',
      precautions: ['Protect from rain for 24 hours after application.'],
    },
    datasheet: 'datasheets/rocketex.pdf',
    pairs_with: ['weatherguard', 'supermatt'],
  },

  /* ------------------------------------------------------------
     7. GLOSS ENAMEL PAINT 
     Label verbatim source: GLOSS ENAMEL PAINT 4LTRS 1.pdf
  ------------------------------------------------------------ */
  {
    slug: 'gloss-enamel',
    name: 'Gloss Enamel',
    tagline: 'Tough high-sheen finish for wood & metal',
    cat: 'enamel',
    cat_label: 'Gloss Enamel · Wood & Metal',
    grade: 'Economy',
    kebs: '',
    brandClass: 'brand-gloss',
    primary: '#0f1f5c',
    accent: '#1e3a8a',
    image: 'images/buckets/GLOSS ENAMEL 4L.jpg',
    sizes: ['250ml', '1L', '4L'],
    short: 'Oil-based gloss enamel for interior and exterior wood, metal and plaster. Tough, durable high-sheen finish with good knock and scuff resistance, excellent hiding power and UV fastness.',
    full: 'Cloud Enamel Paint is a high VOC content gloss enamel finish and washable oil-based product, suitable for interior and exterior use. Gives a tough, durable high-sheen finish on wood, metal and plaster providing good resistance to knocking and scuffing. Can be applied over most previously painted surfaces without an undercoat. On new surfaces apply over the top of a suitable primer and undercoat. A fast-drying enamel manufactured to provide a strong paint film with good chemical resistance; a selection of high-quality pigments further enhances the properties by providing improved weathering resistance and UV light fastness of the coating.',
    features: [
      'Excellent durability',
      'Fully washable',
      'Stain & dirt resistant',
      'Good hiding power',
      'Interior & exterior use',
      'Fast drying',
    ],
    specs: {
      'Coverage':   '13 m² per litre (over Cloud Universal Undercoat on smooth surface)',
      'Touch dry':  '40 minutes',
      'Hard dry':   '16 hours',
      'Recoat':     '16 hours',
      'Finish':     'High gloss',
      'Thinning':   'Cloud White Spirit (if required)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Industrial Brush White Spirit (1L or 5L)',
    },
    claims: [
      'Excellent durability · Fully washable',
      'Stain & dirt resistant · Good hiding power',
      'Tough, durable high-sheen finish on wood, metal and plaster.',
    ],
    uses: [
      'New and previously painted cement plaster, asbestos/fibre cement',
      'Primed metal and wooden surfaces',
      'Steel door and window frames, interior walls, kitchen and bathroom walls, gates, steel fencing',
      'Garden tools, plaques and models',
    ],
    surfaces: ['Wood', 'Metal', 'Plaster', 'Cement', 'Asbestos/fibre cement', 'Previously painted enamel surfaces'],
    application: {
      prep: 'Ensure surface is clean, dry and free from dust, grease and flaking paint.',
      new_surface: 'Apply over the top of a suitable primer and undercoat. For bare wood and timber, we recommend applying a suitable wood primer such as Penetrating Wood Primer.',
      previously_painted: 'Can be applied over most previously painted surfaces without an undercoat. Sand glossy surfaces lightly to provide a key.',
      method: 'Use rollers, brush or spray to apply. Stir well before use.',
      cleanup: 'Clean paint brushes, rollers and spray equipment with Cloud Industrial Brush White Spirit (1L or 5L).',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'High VOC — oil-based · use in well-ventilated areas',
      storage: 'Store in suitable natural weather conditions. Exposure to direct sun or extreme cold may affect quality and shelf life. Keep container tightly closed.',
      first_aid: 'Avoid contact with the eye. If this occurs, wash with water and follow doctor\'s instructions. Keep away from the reach of children. Do not use after unpacking in food preservation.',
      disposal: 'The product is free of environmental pollutants. Dispose of leftover product in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: 'datasheets/gloss-enamel.pdf',
    pairs_with: ['universal-undercoat', 'metal-primer', 'super-gloss', 'white-spirit'],
  },

  /* ------------------------------------------------------------
     8. SUPER GLOSS 
     Label verbatim source: Cloud Paints Combined 2.pdf
  ------------------------------------------------------------ */
  {
    slug: 'super-gloss',
    name: 'Super Gloss',
    tagline: 'Quick-dry high gloss for wood & metal',
    cat: 'enamel',
    cat_label: 'Trade Gloss Enamel',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-gloss',
    primary: '#1e3a8a',
    accent: '#3b5bdb',
    image: 'images/buckets/SUPER GLOSS 4L.jpg',
    sizes: ['1L', '4L', '20L'],
    short: 'Superior alkyd-based high gloss with excellent flow, giving surfaces a tough, durable high-gloss finish. Touch-dry in 1 hour. Formulated for tropical coastal weather conditions.',
    full: 'Cloud Super High Gloss is an alkyd-based superior Solvent-based formulation which offers excellent flow, giving surfaces a tough, durable high gloss finish. Cloud Super Gloss is formulated to offer maximum durability in extreme tropical coastal weather conditions. Self-undercoating, wipeable, non-yellowing. Suitable for use on plaster, wallboards, brickwork and stonework etc., over the appropriate primer and undercoat.',
    features: [
      'Low odour · convenient & pleasant to use',
      'High sheen · UV resistant',
      'Quick dry · touch dry in 1 hour',
      'Fully washable · long-lasting protection',
      'Low VOC',
      'No added lead or mercury',
    ],
    specs: {
      'Coverage':   '13–15 m² per litre (over Cloud Universal Undercoat on smooth surface)',
      'Touch dry':  '1 hour',
      'Through dry': '4 hours',
      'Recoat':     '16 hours',
      'Finish':     'Full high gloss',
      'Thinning':   'White Spirit (to required viscosity for spray)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Cloud White Spirit',
    },
    claims: [
      'High gloss · Quick dry · Lasting protection',
      'For wood & metal.',
      'Touch dry in 1 hour.',
    ],
    uses: [
      'Doors, cabinets, trims, furniture and exterior wood work',
      'Interior and exterior wood and metal',
      'Radiators',
      'Plaster, wallboards, brickwork and stonework',
    ],
    surfaces: ['Wood', 'Metal', 'Plaster', 'Wallboards', 'Brickwork', 'Stonework'],
    application: {
      prep: 'Ensure surface is clean, dry and free from dust, grease and flaking paint. Lightly sand glossy surfaces.',
      new_surface: 'Apply over the appropriate primer and undercoat (Cloud Universal Undercoat or Metal Primer as appropriate).',
      previously_painted: 'Sand to provide a key. Spot-prime bare areas before top coating.',
      method: 'Use soft brush or roller for application. Thin to the required viscosity with White Spirit for spray. Avoid over-thinning. Stir well before use.',
      cleanup: 'After use, remove as much paint as possible from brushes before cleaning with Cloud White Spirit.',
    },
    safety: {
      lead: 'No added lead or mercury',
      voc: 'Low VOC (for an oil-based gloss) · use in well-ventilated areas',
      storage: 'Store in suitable natural weather conditions. Product exposure to direct sun or extreme cold may affect quality and shelf life. Keep lid tightly closed.',
      first_aid: 'Avoid contact with the eye. If this occurs, wash with water and follow doctor\'s instructions. Keep away from the reach of children. Do not use after unpacking in food preservation.',
      disposal: 'The product is free of environmental pollutants. Dispose of in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: 'datasheets/super-gloss.pdf',
    pairs_with: ['universal-undercoat', 'metal-primer', 'white-spirit'],
  },

  /* ------------------------------------------------------------
     9. ROOF PAINT 
     Label verbatim source: ROOF PAINT 4L.pdf
  ------------------------------------------------------------ */
  {
    slug: 'roof-paint',
    name: 'Roof Paint',
    tagline: 'Quality durable flexible roof coating',
    cat: 'specialty',
    cat_label: 'Roof & Metal Coating',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-roof',
    primary: '#8b1e2c',
    accent: '#d92843',
    image: 'images/buckets/ROOF PAINT 4L.jpg',
    sizes: ['1L', '4L', '20L'],
    short: 'High-quality durable flexible coating for galvanised roofs and exposed steelwork. Unique formulation withstands extreme weather variations. Available in Green, Red Oxide, Granite Grey and 17 special colours.',
    full: 'Cloud Roof Paint is a high-quality durable, flexible, beautiful coating for the protection of galvanised roofs and exposed steelwork. Manufactured from the finest light-fast pigments ground in a flexible medium paint product. Its unique formulation provides a flexible coating to withstand extreme variations in various weather conditions. It has excellent hiding power. One finishing coat is normally sufficient for redecoration work.',
    features: [
      'Quality durable',
      'Flexible coating',
      'Beautiful semi-gloss finish',
      'Excellent hiding power',
      'Weather resistant',
      'For galvanised roofs & steelwork',
    ],
    specs: {
      'Coverage':   '10–12 m² per litre (on smooth, non-porous surfaces)',
      'Recoat':     '16 hours',
      'Finish':     'Semi-gloss',
      'Thinning':   'Cloud White Spirit (if required for spray)',
      'Application': 'Brush · Spray (roller on flat surfaces)',
      'Cleaner':    'Cloud White Spirit',
      'Colours':    'Green · Red Oxide · Granite Grey (+17 on request)',
    },
    claims: ['Quality durable', 'Flexible', 'Beautiful coating'],
    uses: [
      'Galvanised (G.C.I.) roofing sheets',
      'Exposed steelwork',
      'Re-decorating previously painted roofs',
      'Industrial and residential metal roofs',
    ],
    surfaces: ['Galvanised sheets (G.C.I.)', 'Weathered galvanised metal', 'Previously painted roof sheets', 'Exposed steelwork'],
    application: {
      prep: 'Prepare surface. Clean thoroughly. Remove rust, dust and loose material.',
      new_surface: 'For new (unweathered) galvanised surfaces / G.C.I. sheets — degrease and prepare surface. Cloud Zinc Phosphate single coat can be applied as primer.',
      previously_painted: 'Prepare surface. Patch-prime with appropriate primer on bare metal surfaces only. Apply 1–2 coats of Cloud Roof Paint.',
      method: 'Apply by brush or spray on corrugated surfaces. Roller can be used on flat surfaces. Stir well before use. Avoid over-thinning — opacity will be affected.',
      cleanup: 'Use Cloud Standard Thinner or Cloud White Spirit for cleaning equipment.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Oil-based · use in well-ventilated areas',
      storage: 'Store in a cool, dry place. Keep lid tightly closed.',
      first_aid: 'Avoid contact with the eye. If this occurs, wash with water and follow doctor\'s instructions.',
      disposal: 'Dispose of in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: 'datasheets/roof-paint.pdf',
    pairs_with: ['metal-primer', 'weatherguard', 'white-spirit'],
  },

  /* ------------------------------------------------------------
     10. ROAD MARKING PAINT 
     Label verbatim source: ROOF PAINT 4L.pdf (combined document)
  ------------------------------------------------------------ */
  {
    slug: 'road-marking',
    name: 'Road Marking Paint',
    tagline: 'High-opacity fast-drying road marking',
    cat: 'specialty',
    cat_label: 'Road & Line Marking',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-floor',
    primary: '#1a202c',
    accent: '#4a5568',
    image: 'images/buckets/ROAD MARKING 4L.jpg',
    sizes: ['1L', '4L', '20L'],
    short: 'Single-pack fast-drying road marking paint on a durable alkyd-modified chlorinated rubber resin. Clean high-visibility lines on concrete and bitumen. White, yellow and black.',
    full: 'Cloud Road Marking Paint is a single pack fast drying coating based on a durable alkyd-modified chlorinated rubber resin. It is most suitable for concrete and bitumen surfaces without bleeding or discolouration, providing clean lines of high visibility. Manufactured from high-quality pigments and a mixture of high-quality resins for added durability. Advantages: good flexibility, excellent adhesion and quick drying.',
    features: [
      'Hardwearing',
      'Excellent adhesion',
      'High opacity',
      'Quick drying',
      'Solvent based',
      'For interior & exterior use',
    ],
    specs: {
      'Coverage':   '2.5–3 m² per litre @ 175µm WFT (per KEBS spec)',
      'Touch dry':  '4–10 minutes',
      'Finish':     'Matt',
      'Thinning':   'Cloud Road Marking Thinner · avoid over-thinning',
      'Application': 'Brush · Spraying machine',
      'Cleaner':    'Cloud Road Marking Paint Thinner',
      'Colours':    'White · Yellow · Black',
    },
    claims: [
      'Hardwearing · Excellent adhesion · High opacity',
      'Can be used on bitumen surfaces, marking of parking areas and sign writing on roads.',
    ],
    uses: [
      'Highways and urban roads',
      'Parking lot line marking',
      'Warehouse and factory floor lines',
      'Sign writing on bitumen and concrete',
    ],
    surfaces: ['Concrete', 'Bitumen', 'Asphalt'],
    application: {
      prep: 'Use dry, clean brush. Remove all dirt from the surface and remove any loose chippings. Ensure the surface is perfectly dry at the time of painting.',
      new_surface: 'Apply directly — no primer required on clean concrete or bitumen.',
      previously_painted: 'Remove loose paint. Clean surface thoroughly before re-coating.',
      method: 'Apply generously by brush, 1 coat of Cloud Road Marking Paint. Avoid excessive over-brushing. For machine application, thin to the required spray viscosity with Cloud Roadline Thinner. Stir well before use.',
      cleanup: 'Clean equipment immediately with Cloud Road Marking Paint Thinner.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Solvent-based · use in well-ventilated areas',
      storage: 'Store in a cool, dry place. Keep lid tightly closed.',
      first_aid: 'Avoid contact with eyes and skin. In case of eye contact, wash with water and seek medical advice.',
      disposal: 'Dispose of in accordance with local regulations. Contain spillage with sand or earth.',
      flammable: 'Flammable — keep away from flames and sources of ignition.',
    },
    datasheet: 'datasheets/road-marking.pdf',
    pairs_with: ['standard-thinner', 'floor-paint'],
  },

  /* ------------------------------------------------------------
     11. METAL PRIMER  — no individual label PDF
     Industry-standard alkyd anti-corrosive primer.
  ------------------------------------------------------------ */
  {
    slug: 'metal-primer',
    name: 'Metal Primer',
    tagline: 'Anti-corrosive primer for ferrous metal',
    cat: 'undercoat',
    cat_label: 'Metal Primer',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-undercoat',
    primary: '#4a5568',
    accent: '#718096',
    image: 'images/buckets/METAL PRIMER 4L.jpg',
    sizes: ['1L', '4L', '20L'],
    short: 'Alkyd-based anti-corrosive primer for ferrous metal surfaces. Creates a tight, durable bond with the substrate and acts as the perfect foundation for Cloud Paints gloss enamel top coats.',
    full: 'Cloud Paints Metal Primer is an alkyd-based anti-corrosive primer formulated specifically for ferrous metal surfaces. Creates a tight, durable bond with the substrate and acts as the perfect undercoat foundation for any of our gloss enamel or industrial top coats. Inhibits rust and extends the service life of exposed steelwork.',
    features: [
      'Anti-corrosive',
      'Excellent adhesion to steel',
      'Rust prevention',
      'Fast drying',
      'For interior & exterior metal',
      'Easy to apply',
    ],
    specs: {
      'Coverage':   '12 m² per litre (on smooth surface)',
      'Touch dry':  '1 hour',
      'Recoat':     '4 hours',
      'Finish':     'Matt primer',
      'Thinning':   'Cloud White Spirit (if required)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Cloud White Spirit',
    },
    claims: ['Anti-corrosive', 'Excellent adhesion', 'Rust prevention'],
    uses: [
      'Steel gates, grilles and security bars',
      'Steel fencing and balustrades',
      'Iron sheets and metal furniture',
      'Undercoat before Cloud Gloss Enamel',
    ],
    surfaces: ['Mild steel', 'Iron', 'Galvanised metal', 'Ferrous metal surfaces'],
    application: {
      prep: 'Remove all rust, loose paint, grease and dirt. Wire-brush or sand to bright metal where possible. Ensure surface is dry before painting.',
      new_surface: 'Apply directly to clean, dry ferrous metal. One full coat is normally sufficient before top-coating.',
      previously_painted: 'Spot-prime bare areas only. Lightly sand sound paintwork to provide a key.',
      method: 'Apply by brush, roller or spray. Stir well before use. Avoid over-thinning.',
      cleanup: 'Clean equipment with Cloud White Spirit immediately after use.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Solvent-based · use in well-ventilated areas',
      storage: 'Store in a cool, dry place. Keep lid tightly closed.',
      first_aid: 'Avoid contact with eyes and skin. In case of eye contact, wash with water and seek medical advice.',
      disposal: 'Dispose of in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: '',
    pairs_with: ['gloss-enamel', 'super-gloss', 'white-spirit'],
  },

  /* ------------------------------------------------------------
     12. UNIVERSAL UNDERCOAT  — no individual label PDF
     Referenced as "Cloud Universal Undercoat" on Gloss Enamel
     and Super Gloss labels.
  ------------------------------------------------------------ */
  {
    slug: 'universal-undercoat',
    name: 'Universal Undercoat',
    tagline: 'Smooth foundation for any top coat',
    cat: 'undercoat',
    cat_label: 'Universal Undercoat',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-undercoat',
    primary: '#718096',
    accent: '#a0aec0',
    image: 'images/buckets/UNIVERSAL UNDERCOAT 4L.jpg',
    sizes: ['1L', '4L', '20L'],
    short: 'All-purpose solvent-based undercoat for interior and exterior wood, metal and primed masonry. The standard base coat for Cloud Gloss Enamel and Super Gloss.',
    full: 'Cloud Universal Undercoat is the companion product to Cloud Gloss Enamel and Super Gloss — a solvent-based alkyd undercoat providing excellent adhesion, fill and a uniform base for any oil-based top coat. Saves time, promotes even sheen in the topcoat and ensures truer final colour. Suitable for wood, primed metal and primed masonry.',
    features: [
      'Excellent adhesion',
      'Uniform smooth base',
      'Saves topcoat',
      'For wood, metal & masonry',
      'Quick drying',
      'Easy to apply',
    ],
    specs: {
      'Coverage':   '12–14 m² per litre',
      'Touch dry':  '1 hour',
      'Recoat':     '4 hours',
      'Finish':     'Matt — designed to be over-coated',
      'Thinning':   'Cloud White Spirit (if required)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Cloud White Spirit',
    },
    claims: ['Excellent adhesion', 'Uniform smooth base', 'Saves topcoat'],
    uses: [
      'Base coat before Cloud Gloss Enamel or Super Gloss',
      'Doors, window frames, furniture',
      'Primed metal gates and grilles',
      'Previously painted wood requiring a fresh base',
    ],
    surfaces: ['Wood', 'Primed metal', 'Previously painted surfaces', 'Primed masonry'],
    application: {
      prep: 'Surface must be clean, dry and free of dust, grease and flaking paint. Lightly sand glossy surfaces to provide a key.',
      new_surface: 'Apply directly to clean, sound wood. For bare metal, apply Cloud Metal Primer first.',
      previously_painted: 'Lightly sand and clean. One coat of undercoat is normally sufficient before top-coating.',
      method: 'Apply by brush, roller or spray. Stir well before use.',
      cleanup: 'Clean tools with Cloud White Spirit immediately after use.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Solvent-based · use in well-ventilated areas',
      storage: 'Store in a cool, dry place. Keep lid tightly closed.',
      first_aid: 'Avoid contact with eyes and skin. In case of eye contact, wash with water and seek medical advice.',
      disposal: 'Dispose of in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: '',
    pairs_with: ['gloss-enamel', 'super-gloss', 'metal-primer'],
  },

  /* ------------------------------------------------------------
     13. CLEAR VARNISH 
     Label verbatim source: Cloud Paints Combined 1.pdf
  ------------------------------------------------------------ */
  {
    slug: 'clear-varnish',
    name: 'Clear Varnish',
    tagline: 'Superior scratch-resistant clear gloss',
    cat: 'wood',
    cat_label: 'Wood Varnish · Clear Gloss',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-varnish',
    primary: '#92400e',
    accent: '#d69e2e',
    image: 'images/buckets/CLEAR VARNISH 4L.jpg',
    sizes: ['1L', '4L', '20L'],
    short: 'Quick-drying multipurpose clear varnish for interior woodwork. Blend of modified polyurethane alkyd resin and hardening agent that preserves the natural beauty of timber.',
    full: 'Cloud Multipurpose Clear Varnish is a quick-drying clear varnish formulated to produce a tough, gloss finish on interior woodwork. Recommended for use as a furniture finish and for general application on new or sanded door panels and frames, counters, timber pelmets, skirting boards, wall partitions etc. Manufactured from a blend of high-quality oil-modified polyurethane alkyd resin and a special hardening resin that maintains the natural beauty of the timber. Retains the natural beauty of timber · High spreading capacity and quick drying · Tough, hard-wearing abrasion-resistant clear gloss finish.',
    features: [
      'Superior scratch resistant',
      'Maximum durability',
      'Fast dry time',
      'High spreading capacity',
      'Retains natural beauty of timber',
      'Abrasion resistant',
    ],
    specs: {
      'Coverage':   '12–15 m² per litre (on smooth, non-porous surfaces)',
      'Touch dry':  '3–4 hours',
      'Recoat':     '12–16 hours',
      'Finish':     'Clear gloss',
      'Thinning':   'Cloud White Spirit',
      'Application': 'Brush (working well into grain)',
      'Cleaner':    'Cloud White Spirit',
      'Coats':      '2–3 recommended',
    },
    claims: ['Superior scratch resistant', 'Maximum durability', 'Fast dry time'],
    uses: [
      'Doors, trim, furniture and joinery',
      'Counters and timber pelmets',
      'Skirting boards and wall partitions',
      'Interior woodwork requiring a clear protective finish',
    ],
    surfaces: ['Interior woodwork', 'New timber', 'Previously varnished wood (properly prepared)'],
    application: {
      prep: 'Ensure wood is clean, dust-free and defective or poorly adhering material removed. Rub down with abrasive paper and dust off.',
      new_surface: 'Apply a minimum of 3 coats Cloud Multipurpose Clear Varnish. On new bare timber, the first coat should be thinned to ease brushing consistency using Cloud White Spirit. Subsequent coats can be thinned if necessary.',
      previously_painted: 'For previously varnished woodwork — unsound timber: remove all old and damaged varnish down to bare surface. If necessary, use Cloud Paint and Varnish Remover and/or mechanical sanding equipment. Prepare surface as for new timber. Apply 3 coats Cloud Multipurpose Clear Varnish.',
      method: 'By brush, working well into the surface to get good penetration and adhesion on wood. Not recommended for floors. Finish high gloss — the latter is not recommended for use on floors.',
      cleanup: 'Clean all equipment with Cloud White Spirit immediately after use.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Solvent-based · use in well-ventilated areas',
      storage: 'Store in dry conditions and protect from extreme temperatures.',
      first_aid: 'Do not empty into drains or watercourses. In case of accident, collect spillage using sand or earth. Do not empty into drains or watercourses. Avoid long-term adverse effects on the aquatic environment.',
      disposal: 'Dispose of any paint waste in accordance with the appropriate environment quality regulations.',
      flammable: 'Flammable — keep out of reach of children and away from sources of ignition. In case of fire use foam, CO₂ powder. Use in a well-ventilated area.',
    },
    datasheet: 'datasheets/clear-varnish.pdf',
    pairs_with: ['varnish-stain', 'white-spirit', 'turpentine'],
  },

  /* ------------------------------------------------------------
     14. VARNISH STAIN  — no individual label PDF
     Aligned with Clear Varnish technical profile.
  ------------------------------------------------------------ */
  {
    slug: 'varnish-stain',
    name: 'Varnish Stain',
    tagline: 'Tinted varnish for rich wood tones',
    cat: 'wood',
    cat_label: 'Wood Varnish · Tinted',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-varnish',
    primary: '#7c2d12',
    accent: '#c2410c',
    image: 'images/buckets/VARNISH STAIN 4L.jpg',
    sizes: ['1L', '4L', '20L'],
    short: 'Tinted polyurethane alkyd varnish that stains and protects in a single coat. Deepens the natural look of wood with rich classic tones.',
    full: 'Cloud Paints Varnish Stain combines colour and protection in a single coat — adding rich, classic wood tones while sealing and protecting the surface. Built on the same polyurethane alkyd platform as Cloud Clear Varnish for hard-wearing, abrasion-resistant performance. Perfect for furniture, doors and trim where you want to deepen the natural look of wood without painting over the grain.',
    features: [
      'Stain + varnish in one coat',
      'Rich classic wood tones',
      'UV resistant',
      'Hard-wearing finish',
      'Retains wood grain visibility',
      'Long lasting',
    ],
    specs: {
      'Coverage':   '12–15 m² per litre',
      'Touch dry':  '3–4 hours',
      'Recoat':     '12–16 hours',
      'Finish':     'Tinted gloss',
      'Thinning':   'Cloud White Spirit',
      'Application': 'Brush · Cloth wipe',
      'Cleaner':    'Cloud White Spirit',
      'Colours':    'Mahogany · Walnut · Teak · Oak · Ebony',
    },
    claims: ['Stain + varnish in one coat', 'Rich classic wood tones', 'UV resistant'],
    uses: [
      'Furniture, doors and trim',
      'Interior joinery',
      'Enhancing natural wood grain with a warm tint',
      'Restoration of tired timber surfaces',
    ],
    surfaces: ['Interior woodwork', 'New timber', 'Previously stained wood (properly prepared)'],
    application: {
      prep: 'Clean wood thoroughly. Sand to remove defective material. Ensure surface is dust-free and dry.',
      new_surface: 'Apply 2–3 coats. First coat may be thinned slightly with Cloud White Spirit to aid penetration.',
      previously_painted: 'Remove old varnish or stain as needed. Sand to bare timber for best results.',
      method: 'Apply with brush, working well into the grain. Wipe excess with a lint-free cloth for an even tone. Stir well before use.',
      cleanup: 'Clean brushes with Cloud White Spirit immediately after use.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Solvent-based · use in well-ventilated areas',
      storage: 'Store in a cool, dry place. Keep lid tightly closed.',
      first_aid: 'Avoid contact with eyes and skin. In case of eye contact, wash with water and seek medical advice.',
      disposal: 'Dispose of in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: '',
    pairs_with: ['clear-varnish', 'white-spirit'],
  },

  /* ------------------------------------------------------------
     15. FLOOR PAINT  — no individual label PDF
     Industry-standard alkyd floor coating.
  ------------------------------------------------------------ */
  {
    slug: 'floor-paint',
    name: 'Floor Paint',
    tagline: 'Heavy-duty coating for industrial & residential floors',
    cat: 'specialty',
    cat_label: 'Floor Coating',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-floor',
    primary: '#2d3748',
    accent: '#4a5568',
    image: 'images/buckets/FLOOR PAINT 4L.jpg',
    sizes: ['4L', '20L'],
    short: 'Hard-wearing alkyd-based floor coating for concrete and wooden floors. Resists abrasion, chemicals, oil spills and heavy foot traffic. Built for warehouses, garages and residential floors.',
    full: 'Cloud Paints Floor Paint is a heavy-duty alkyd-based coating designed for concrete, wooden and industrial floors. Resists abrasion, chemicals, oil spills and heavy foot traffic. Ideal for warehouses, garages, workshops, factory floors and residential utility areas. Delivers a tough semi-gloss finish that is easy to clean and stands up to years of wear.',
    features: [
      'Heavy-duty coating',
      'Abrasion resistant',
      'Chemical & oil resistant',
      'For concrete & wood floors',
      'Industrial grade',
      'Easy to clean',
    ],
    specs: {
      'Coverage':   '10–12 m² per litre',
      'Touch dry':  '4 hours',
      'Recoat':     '12 hours',
      'Finish':     'Semi-gloss',
      'Thinning':   'Cloud White Spirit (if required)',
      'Application': 'Brush · Roller',
      'Cleaner':    'Cloud White Spirit',
      'Colours':    'Red Oxide · Green · Grey',
    },
    claims: ['Heavy-duty', 'Abrasion resistant', 'Chemical resistant'],
    uses: [
      'Warehouses and factory floors',
      'Garages and workshops',
      'Residential utility and balcony floors',
      'Line marking on industrial floors',
    ],
    surfaces: ['Concrete', 'Wood', 'Previously painted floor surfaces'],
    application: {
      prep: 'Concrete must be fully cured (minimum 28 days). Remove all dust, laitance, oil and grease. Acid-etch or mechanically abrade smooth concrete for adhesion.',
      new_surface: 'First coat may be thinned 10% with Cloud White Spirit to aid penetration on porous concrete. Follow with one to two full-strength coats.',
      previously_painted: 'Remove loose and flaking paint. Sand glossy areas to provide a key. Spot-prime bare concrete before over-coating.',
      method: 'Apply by brush or roller. Stir well before use. Allow full recoat interval between coats.',
      cleanup: 'Clean equipment with Cloud White Spirit immediately after use.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Solvent-based · use in well-ventilated areas',
      storage: 'Store in a cool, dry place. Keep lid tightly closed.',
      first_aid: 'Avoid contact with eyes and skin. In case of eye contact, wash with water and seek medical advice.',
      disposal: 'Dispose of in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: '',
    pairs_with: ['road-marking', 'standard-thinner'],
  },

  /* ------------------------------------------------------------
     16. WHITE SPIRIT  — no individual label PDF
     Paired with Gloss Enamel, Super Gloss, Clear Varnish.
  ------------------------------------------------------------ */
  {
    slug: 'white-spirit',
    name: 'White Spirit',
    tagline: 'High-purity thinner & equipment cleaner',
    cat: 'solvent',
    cat_label: 'Solvent · Thinner',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-thinner',
    primary: '#a0aec0',
    accent: '#cbd5e0',
    image: 'images/buckets/WHITE SPIRIT 4L.jpg',
    sizes: ['1L', '5L', '20L'],
    short: 'High-purity petroleum distillate for thinning oil-based paints, varnishes and enamels, and for cleaning brushes, rollers and spray equipment. Pairs with the Cloud Gloss and Varnish range.',
    full: 'Cloud Paints White Spirit is a high-purity petroleum distillate solvent for thinning oil-based paints, varnishes, enamels and stains. Also ideal for cleaning brushes, rollers and spray equipment, and for removing fresh paint splashes from hard surfaces. The standard cleanup solvent for the Cloud Gloss Enamel, Super Gloss, Roof Paint and Clear Varnish range.',
    features: [
      'High purity',
      'Paint thinner',
      'Tool cleaner',
      'Multi-purpose',
      'Professional grade',
      'Fast evaporating',
    ],
    specs: {
      'Use':         'Thinning · Equipment cleaning',
      'Type':        'Petroleum distillate',
      'Application': 'Mixing · Cleaning',
      'Flash point': '38°C (closed cup, typical)',
      'Storage':     'Cool, dry, well-ventilated place',
      'Cleaner':     'Not applicable (is the cleaner)',
    },
    claims: ['High purity', 'Paint thinner & tool cleaner', 'Professional grade'],
    uses: [
      'Thinning Cloud Gloss Enamel and Super Gloss',
      'Thinning Cloud Clear Varnish',
      'Cleaning brushes, rollers and spray equipment',
      'Removing fresh oil-based paint splashes',
    ],
    surfaces: [],
    application: {
      prep: 'Ensure work area is well ventilated and free of ignition sources.',
      new_surface: 'Not applicable — this is a solvent.',
      previously_painted: 'Not applicable — this is a solvent.',
      method: 'For thinning: add gradually to paint while stirring, to the required viscosity. For cleaning: immerse brushes and work solvent through bristles, then rinse and dry. Do not overthin paint.',
      cleanup: 'Dispose of used solvent responsibly — do not pour down drains.',
    },
    safety: {
      lead: 'Not applicable',
      voc: 'Petroleum distillate · flammable vapour',
      storage: 'Store in a cool, dry, well-ventilated place away from heat, flames and sparks. Keep container tightly closed.',
      first_aid: 'In case of eye contact, flush with plenty of water and seek medical attention. If swallowed, do NOT induce vomiting — seek immediate medical attention. If inhaled, move to fresh air.',
      disposal: 'Dispose of as flammable waste in accordance with local regulations. Do not pour into drains or watercourses.',
      flammable: 'Flammable liquid and vapour. DANGER — keep away from heat, flames, sparks, sunlight and static.',
    },
    datasheet: '',
    pairs_with: ['gloss-enamel', 'super-gloss', 'clear-varnish', 'roof-paint'],
  },

  /* ------------------------------------------------------------
     17. TURPENTINE 
     Label verbatim source: Cloud Paints Combined 5.pdf
  ------------------------------------------------------------ */
  {
    slug: 'turpentine',
    name: 'Turpentine',
    tagline: 'Pine-derived professional thinner',
    cat: 'solvent',
    cat_label: 'Solvent · Natural',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-thinner',
    primary: '#9ca3af',
    accent: '#d1d5db',
    image: 'images/buckets/TURPENTINE 5L.jpg',
    sizes: ['1L', '5L', '20L'],
    short: 'Professional-quality pine-tree-derived thinner for oil-based paints, enamels and varnishes. Multi-purpose — removes grease and grime, cleans brushes, dissolves polish components. Meets Federal Specification TT-T-801 C Type 1.',
    full: 'Turpentine Paint Remover is a pine tree-derived, professional-quality thinner for oil-based paints, enamels and varnishes. Cloud Turpentine is a multi-purpose product that can be used for many applications such as removing grease, grime from surfaces, as well as cleaning paintbrushes and paint rollers used with solvent-based paints such as Gloss Enamel, Primers and Varnishes etc. It can also be used for thinning down or spraying alkyd-based decorative paints. Can be used to dissolve polish components, e.g. Beeswax. Removes tar, grease and tree sap. Meets Federal Specification TT-T-801 C Type 1.',
    features: [
      'Pine tree-derived',
      'Professional quality',
      'Paint thinner for alkyd paints and varnishes',
      'Cleans brushes, rollers and spray equipment',
      'Suitable for spray applications',
      'Removes tar, grease and tree sap',
    ],
    specs: {
      'Use':         'Thinning · Cleaning · Grease removal',
      'Type':        'Natural pine-tree turpentine',
      'Application': 'Mixing · Cleaning · Spray thinning',
      'Standard':    'Federal Specification TT-T-801 C Type 1',
      'Storage':     'Cool, dry, well-ventilated place',
    },
    claims: [
      'Paint thinner for alkyd paints and varnishes.',
      'Cleans brushes, rollers and spray equipment.',
      'Meets Federal Specification TT-T-801 C Type 1.',
    ],
    uses: [
      'Thinning Cloud Gloss Enamel, Primers and Varnishes',
      'Cleaning brushes, rollers and spray equipment',
      'Dissolving polish components (e.g. Beeswax)',
      'Removing tar, grease and tree sap',
    ],
    surfaces: [],
    application: {
      prep: 'Use within well-ventilated areas. Keep away from heat, flames, sunlight, static and electrical sparks.',
      new_surface: 'Not applicable — this is a solvent.',
      previously_painted: 'Not applicable — this is a solvent.',
      method: 'For thinning: add gradually to paint while stirring. For cleaning: immerse brushes and work solvent through bristles, then rinse and dry.',
      cleanup: 'Secure cap tightly after use. Keep upright at all times.',
    },
    safety: {
      lead: 'Not applicable',
      voc: 'Natural hydrocarbon solvent · flammable vapour',
      storage: 'Store product in cool, well-ventilated area. Ensure cap is tightly sealed and packaging is secure and upright at all times. Secure product when transporting to prevent accidental spillage.',
      first_aid: 'If overexposed to fumes, move victim to fresh air and seek immediate medical attention. Use protective glasses — if contact with eyes occurs, flush open eyes with plenty of water and seek immediate medical attention. Causes mild skin irritation — wear protective gloves and avoid skin contact. Do not eat, drink or smoke when using. Take off contaminated clothing and wash before re-use. If swallowed, do NOT induce vomiting — seek immediate medical attention.',
      disposal: 'Dispose of container — do not use for any other purpose. Do not dispose of product into common waste system.',
      flammable: 'WARNING — Flammable liquid and vapour. DANGER: May be fatal if swallowed and enters airways. Toxic to aquatic life. Avoid release to the environment. Do not inhale vapour. In the event of a fire, use Carbon Dioxide Foam or Chemical Powder — NOT water.',
    },
    datasheet: 'datasheets/turpentine.pdf',
    pairs_with: ['gloss-enamel', 'clear-varnish', 'super-gloss'],
  },

  /* ------------------------------------------------------------
     18. STANDARD THINNER  — no individual label PDF
     Referenced on Roof Paint label as a cleaner option.
  ------------------------------------------------------------ */
  {
    slug: 'standard-thinner',
    name: 'Standard Thinner',
    tagline: 'Universal hydrocarbon thinner for the trade',
    cat: 'solvent',
    cat_label: 'Solvent · Universal',
    grade: 'Trade',
    kebs: '',
    brandClass: 'brand-thinner',
    primary: '#cbd5e0',
    accent: '#e2e8f0',
    image: 'images/buckets/STANDARD THINNER 4L.jpg',
    sizes: ['1L', '4L', '20L'],
    short: 'All-round hydrocarbon-blend thinner for Cloud Paints enamels and undercoats. The contractor\'s choice for high-volume thinning and equipment cleaning across the Cloud solvent-based range.',
    full: 'Cloud Paints Standard Thinner is the universal, all-purpose thinner formulated for use with Cloud Paints enamel paints and undercoats. Compatible with the full Cloud Paints oil-based product range and ideal for cleanup of brushes, rollers and spray equipment. The cost-effective contractor-grade choice for high-volume work.',
    features: [
      'Universal compatibility',
      'Quick drying',
      'Compatible with Cloud oil-based range',
      'Multi-purpose',
      'Cost effective',
      'Professional grade',
    ],
    specs: {
      'Use':         'Thinning · Cleaning',
      'Type':        'Hydrocarbon blend',
      'Application': 'Mixing · Cleaning',
      'Storage':     'Cool, dry, well-ventilated place',
    },
    claims: ['Universal thinner for the Cloud oil-based range', 'Cost-effective contractor grade'],
    uses: [
      'Thinning Cloud Gloss Enamel and Super Gloss',
      'Thinning Cloud Roof Paint',
      'Cleaning brushes, rollers and spray equipment',
      'General cleanup on oil-based paint jobs',
    ],
    surfaces: [],
    application: {
      prep: 'Use within well-ventilated areas. Keep away from heat, flames and sparks.',
      new_surface: 'Not applicable — this is a solvent.',
      previously_painted: 'Not applicable — this is a solvent.',
      method: 'For thinning: add gradually to paint while stirring. For cleaning: immerse brushes and work solvent through bristles, then rinse and dry.',
      cleanup: 'Dispose of used solvent responsibly — do not pour down drains.',
    },
    safety: {
      lead: 'Not applicable',
      voc: 'Hydrocarbon solvent · flammable vapour',
      storage: 'Store in a cool, dry, well-ventilated place away from heat, flames and sparks. Keep container tightly closed.',
      first_aid: 'In case of eye contact, flush with plenty of water and seek medical attention. If swallowed, do NOT induce vomiting — seek immediate medical attention. If inhaled, move to fresh air.',
      disposal: 'Dispose of as flammable waste in accordance with local regulations. Do not pour into drains or watercourses.',
      flammable: 'Flammable liquid and vapour. Keep away from heat, flames and sparks.',
    },
    datasheet: '',
    pairs_with: ['gloss-enamel', 'super-gloss', 'roof-paint'],
  },

];

// Helper for finding a product by slug
window.getProduct = function (slug) {
  return window.CLOUD_PRODUCTS.find(function (p) { return p.slug === slug; });
};
