// ============================================================
// CLOUD PAINTS — Product Catalogue
// ============================================================
// Source-of-truth for the 18-product range. Copy, specs and
// claims transcribed from Cloudsent Decor Ltd. product labels
// (PDFs under Website Info and Media/). Industry-standard
// defaults fill gaps where products have no individual datasheet.
//
// Field contract used across the site:
//   slug, name, tagline, cat, cat_label, grade, kebs, brandClass,
//   primary, accent, image, sizes[], short, full,
//   features[]   — short bullet claims (label-verbatim)
//   specs{}      — quick-view grid (Coverage, Touch dry, Recoat,
//                  Hard dry, Finish, Thinning, Application, Cleaner)
//   uses[]       — real-world use cases
//   surfaces[]   — substrates the label lists
//   claims[]     — verbatim marketing lines (bigger callouts)
//   application{} — prep / new_surface / previously_painted / method
//   safety{}     — storage, first_aid, disposal, voc notes
//   datasheet    — relative path to the PDF for Download button
//   pairs_with[] — cross-sell slugs
// ============================================================

window.CLOUD_PRODUCTS = [

  /* ------------------------------------------------------------
     1. SILK VINYL 
     Label verbatim source: SILK VINYL 4LTS REV SEP.pdf
  ------------------------------------------------------------ */
  {
    slug: 'silk-vinyl',
    surface_tags: ['cement'],
    name: 'Silk Vinyl',
    tagline: 'Luxury You Can See. Quality You Can Feel.',
    cat: 'interior-wall',
    cat_label: 'Interior Wall Paint',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-silk-vinyl',
    primary: '#6b1f6e',
    accent: '#ec4899',
    image: 'images/buckets/SILK VINYL 4LTS REV SEP.jpg',
    sizes: ['20L', '4L', '1L'],
    short: 'A subtle, elegant sheen that adds depth, richness and a premium feel — colours appear more vibrant, and the surface stays easy to clean in busy homes and commercial spaces.',
    full: 'Cloud Paints Silk Vinyl Paint is ideal for creating interiors with a subtle, elegant sheen that adds depth, richness and a premium feel. Unlike matt finishes, silk paint reflects a soft amount of light, making colours appear more vibrant while remaining easy to clean — perfect for busy homes and commercial spaces. Crafted to deliver a smooth, elegant sheen and rich, lasting colour, it combines beauty with durability, giving walls a refined finish that\'s both washable and easy to maintain.',
    features: [
      'Smooth, luxurious silk finish',
      'Rich, vibrant colour appearance',
      'Excellent washability for everyday cleaning',
      'Good stain resistance',
      'High hiding power for an even finish',
      'Durable and long-lasting',
      'Resists fungus growth · No harmful smell',
      'Water based · Lead free',
    ],
    specs: {
      'Coverage':   '10–12 m² per litre',
      'Touch dry':  '1 hour',
      'Recoat':     '3–4 hours',
      'Finish':     'Silky sheen',
      'Thinning':   '10–15% clean water (first coat only)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Clean water',
    },
    claims: ['Luxury You Can See. Quality You Can Feel.', 'Bring your interiors to life — bright, welcoming and effortlessly premium.'],
    uses: [
      'Living Rooms — a sophisticated backdrop that enhances natural light and decorative lighting',
      'Bedrooms — a luxurious, silky appearance that complements modern furniture and soft furnishings',
      'Dining Rooms — adds warmth and elegance, especially when paired with statement lighting',
      'Hallways & Staircases — the durable finish stands up well to high-traffic areas while maintaining its beauty',
      'Home Offices — a polished, professional look that\'s easy to maintain',
    ],
    design_tips: [
      'Pair warm neutral colours with wood accents and brass fixtures for a timeless luxury look.',
      'Use soft greys and whites with black trim for a contemporary aesthetic.',
      'Add 3000K warm-white LED lighting to enhance the gentle sheen of the silk finish.',
      'Combine with a Brilliant White Vinyl Matt ceiling to create a crisp contrast that makes the walls stand out.',
    ],
    surfaces: ['Plaster', 'Concrete', 'Gypsum board', 'Previously painted interior walls'],
    application: {
      prep: 'Surfaces must first be thoroughly cleaned free from all dust and grease objects for a better result.',
      new_surface: 'Cloud Paints Undercoat is advisable to prime the surface before using the top coat of Cloud Paints Silk Vinyl Emulsion, and must be sanded properly for an absolute acceptable finish.',
      previously_painted: 'The surface must be sanded properly for an absolute acceptable finish before using the top coat of Cloud Paints Silk Vinyl Emulsion.',
      method: 'Stir well before use. Can be applied by brush, roller or spray equipment. For first coat on porous surfaces, ease of application and for spray application, paint can be thinned with 10–15% clean water. Avoid over-thinning.',
      cleanup: 'Clean equipment with clean water.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based · no harmful smell',
      storage: 'Store in a cool, dry place, out of direct sunlight. Keep lid tightly closed.',
      first_aid: 'In case of eye contact, rinse with plenty of clean water. If skin contact, wash with soap and water. Seek medical advice if irritation persists.',
      disposal: 'Do not empty into drains or watercourses. Dispose of in accordance with local regulations.',
    },
    datasheet: 'datasheets/silk-vinyl.pdf',
    pairs_with: ['supermatt', 'universal-undercoat', 'vinyl-matt'],
  },

  /* ------------------------------------------------------------
     2. VINYL MATT 
     Label verbatim source: VINYL MATT 4LTS REV SEP.pdf
  ------------------------------------------------------------ */
  {
    slug: 'vinyl-matt',
    surface_tags: ['cement'],
    name: 'Vinyl Matt',
    tagline: 'Brilliant White, Inside and Out.',
    cat: 'interior-wall',
    // Rated for exterior as well as interior, so it lists under both filters.
    cat_extra: ['exterior-wall'],
    cat_label: 'Interior & Exterior Wall Paint',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-vinyl-matt',
    primary: '#1e3a8a',
    accent: '#3b5bdb',
    image: 'images/buckets/VINYL MATT 4LTS REV SEP.jpg',
    sizes: ['20L', '4L', '1L'],
    short: 'A brilliant, long-lasting white with a smooth non-reflective matte finish. Rated for interior and exterior walls and ceilings alike, delivering exceptional whiteness and a refined modern appearance.',
    full: 'Cloud Paints Vinyl Matt – Brilliant White is engineered to transform ordinary ceilings and walls into flawless architectural features, inside the building and out. Featuring our Colour Lock Technology, excellent hiding power and low VOC formulation, it delivers exceptional whiteness and a silky smooth matte finish. The breathable coating helps reduce peeling, the anti-flashing formulation gives a uniform appearance, and the anti-fungal protection keeps the painted area clean for years to come — which is what makes the same tin suitable for a sheltered exterior elevation as well as an interior ceiling.',
    features: [
      'Colour Lock Technology',
      'Excellent hiding power',
      'Low VOC · environment-friendly',
      'Suitable for interior and exterior walls and ceilings',
      'Ultra-smooth, non-reflective matte finish',
      'High whiteness · brilliant white finish',
      'Low splatter during application',
      'Breathable finish that helps reduce peeling',
      'Anti-flashing formulation for uniform appearance',
      'Anti-fungal — does not allow fungal growth on the applied surface',
      'No added lead, mercury, cadmium or chromium',
      'Easy touch-up · low odour',
    ],
    specs: {
      'Coverage':   '10–12 m² per litre',
      'Touch dry':  '1 hour',
      'Recoat':     '3–4 hours',
      'Finish':     'Hard-wearing matt',
      'Suitable for': 'Interior and exterior walls and ceilings',
      'Thinning':   '8–10L of water for a 20L bucket. Stir well and strain thoroughly before use. Dark shades may vary depending on colour.',
      'Application': 'Brush · Microfibre roller · Spray',
      'Cleaner':    'Clean water',
    },
    claims: [
      'Illuminate Every Ceiling with Timeless Elegance.',
      'A ceiling that looks effortlessly clean, beautifully bright, and professionally finished for years to come.',
    ],
    uses: [
      'Homes — flawless smooth-flat or coffered ceilings',
      'Apartments — bright tray ceilings with hidden LED strip lighting',
      'Offices — professional matte ceilings under recessed downlights',
      'Hotels — vaulted and high ceilings for grand entrance halls',
      'Exteriors — sheltered elevations, balconies, walkways and soffits',
      'Schools and institutions',
      'Retail and commercial spaces',
    ],
    inspiration: [
      { title: 'Minimalist smooth flat ceiling',     copy: 'Clean, seamless finish. Best in pure white or warm white. Works well with recessed LED downlights.' },
      { title: 'Coffered ceiling',                   copy: 'Adds depth and luxury. Vinyl matt highlights the architectural details without glare — perfect for formal living and dining rooms.' },
      { title: 'Tray ceiling with hidden LED strip', copy: 'One of the most popular premium designs. Hidden lighting creates a floating effect that looks especially elegant at night.' },
      { title: 'Wooden accent + matte white ceiling',copy: 'Combines warmth with a modern aesthetic. Great for lounges and home offices — the matte white balances the wood tones.' },
      { title: 'Vaulted or high ceiling',            copy: 'Creates an open, airy feeling. Vinyl matt minimises reflections from skylights — ideal for grand entrance halls and open-plan living spaces.' },
    ],
    design_tips: [
      'Use a bright white or soft warm white for maximum light reflection without glare.',
      'Ensure the ceiling is perfectly skimmed and sanded before painting.',
      'Apply one quality primer followed by two coats of Vinyl Matt.',
      'Paint with a microfibre roller to minimise roller marks.',
      'Install warm-white LEDs (2700–3000K) for a soft, luxurious appearance, or neutral white (4000K) for a crisp modern look.',
    ],
    surfaces: ['Plaster', 'Concrete', 'Wood', 'Gypsum', 'Previously painted surfaces'],
    application: {
      prep: 'Surfaces must first be thoroughly cleaned free from all dust and grease objects for a better result.',
      new_surface: 'Cloud Paints Undercoat is advisable to prime the surface before using the top coat of Cloud Paints Vinyl Matt Emulsion and must be sanded properly for an absolute acceptable finish.',
      previously_painted: 'The surface must be sanded properly for an absolute acceptable finish before using the top coat of Cloud Paints Vinyl Matt Emulsion.',
      method: 'Stir well before use. Can be applied by brush, roller or spray equipment. For first coat on porous surfaces, ease of application and for spray application, paint can be thinned with 10–15% clean water. Avoid over-thinning.',
      cleanup: 'Clean equipment with clean water.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based · no harmful smell',
      storage: 'Store in a cool, dry place, out of direct sunlight. Keep lid tightly closed.',
      first_aid: 'In case of eye contact, rinse with plenty of clean water. If skin contact, wash with soap and water. Seek medical advice if irritation persists.',
      disposal: 'Do not empty into drains or watercourses. Dispose of in accordance with local regulations.',
    },
    datasheet: 'datasheets/vinyl-matt.pdf',
    pairs_with: ['weatherguard', 'supermatt', 'universal-undercoat'],
  },

  /* ------------------------------------------------------------
     3. IRIS PLASTIC EMULSION 
     Label verbatim source: IRISH REV 4L SEP.pdf
  ------------------------------------------------------------ */
  {
    slug: 'iris-economy',
    surface_tags: ['cement'],
    name: 'Iris Plastic Emulsion',
    tagline: 'Excellent opacity · Odourless · Eco-friendly',
    cat: 'interior-wall',
    cat_label: 'Interior Wall Paint',
    grade: 'Economy',
    kebs: '',
    brandClass: 'brand-iris',
    primary: '#d4940a',
    accent: '#fbbf24',
    image: 'images/buckets/IRISH REV 4L SEP.jpg',
    sizes: ['20L', '4L', '1L'],
    short: 'Acrylic co-polymer based economy emulsion with a smooth, flat decorative finish and good hiding power. Anti-fungal and anti-bacterial — recommended for interior walls and ceilings.',
    full: 'Cloud Paints Iris Plastic Emulsion is an acrylic co-polymer based quality economical emulsion paint with a smooth, flat and decorative finish with good hiding power. It contains anti-fungal and anti-bacterial additives. It is recommended for masonry application and decoration of interior surfaces like concrete, plaster, gypsum board, asbestos, walls and ceilings.',
    features: [
      'Excellent opacity',
      'Odourless · Eco-friendly',
      'Smooth flat decorative finish',
      'Anti-fungal & anti-bacterial additives',
      'Lead free · Water based',
      'Easy to apply',
    ],
    specs: {
      'Coverage':   '12 m² per litre',
      'Touch dry':  '1 hour',
      'Recoat':     '3–4 hours',
      'Finish':     'Smooth matt',
      'Thinning':   'Water as required (first coat)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Clean water',
    },
    claims: ['Excellent opacity', 'Odourless & eco-friendly', 'For interior walls & ceilings'],
    uses: [
      'Interior walls and ceilings',
      'Masonry decoration on concrete and plaster',
      'Cost-effective choice for high-coverage jobs',
    ],
    surfaces: ['Concrete', 'Plaster', 'Gypsum board', 'Asbestos', 'Walls', 'Ceilings'],
    application: {
      prep: 'Surfaces must first be thoroughly cleaned free from all dust and grease objects for a better result.',
      new_surface: 'Cloud Paints Iris Plastic Emulsion is advisable to prime the surface before using 1 coat of Cloud Paints Undercoat and must be sanded properly for an absolute acceptable finish.',
      previously_painted: 'The surface must be sanded properly for an absolute acceptable finish before using the top coat of Cloud Paints Iris Plastic Emulsion.',
      method: 'Stir well before use. Cloud Paints Iris Plastic Emulsion can be applied by brush, roller or spray equipment.',
      cleanup: 'Clean equipment with clean water.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based · odourless',
      storage: 'Store in a cool, dry place, out of direct sunlight. Keep lid tightly closed.',
      first_aid: 'In case of eye contact, rinse with plenty of clean water. If skin contact, wash with soap and water. Seek medical advice if irritation persists.',
      disposal: 'Do not empty into drains or watercourses. Dispose of in accordance with local regulations.',
    },
    datasheet: 'datasheets/iris-economy.pdf',
    pairs_with: ['supermatt', 'universal-undercoat'],
  },

  /* ------------------------------------------------------------
     4. SUPERMATT EMULSION 
     Label verbatim source: SUPERMATT REV 4L.pdf
  ------------------------------------------------------------ */
  {
    slug: 'supermatt',
    surface_tags: ['cement', 'exterior'],
    name: 'SuperMatt Emulsion',
    tagline: 'Excellent coverage & hiding power',
    cat: 'primer',
    cat_label: 'Wall Primer / Sealer',
    grade: 'Trade',
    kebs: '',
    brandClass: 'brand-supermatt',
    primary: '#b8243a',
    accent: '#d92843',
    image: 'images/buckets/SUPERMATT REV 4L.jpg',
    sizes: ['30kg', '10kg'],
    short: 'Trade-quality water-based emulsion undercoat with excellent coverage, filling properties and a long-lasting bright matt finish. The smooth base for every decorative top coat.',
    full: 'Cloud Paints SuperMatt is a trade quality emulsion paint used for both interior and exterior. A water-based undercoat that has an excellent coverage, finish and application properties. It also provides a smooth base for the top coat application of all decorative products. Its high-quality filling properties has made it ideal for use on all types of interior, exterior and masonry surfaces. Cloud Paints SuperMatt is a high quality, acrylic-based paint, fast drying with a long lasting bright matt finish.',
    features: [
      'Excellent coverage & hiding power',
      'High-quality filling properties',
      'Fast drying',
      'Smooth base for topcoats',
      'Interior & exterior use',
      'Lead free · No harmful smell',
    ],
    specs: {
      'Coverage':   '10–12 m² per litre',
      'Touch dry':  '1 hour',
      'Recoat':     '2–3 hours',
      'Finish':     'Bright matt',
      'Thinning':   '≤25% water (do not exceed)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Water — rinse tools properly for next use',
    },
    claims: ['Excellent coverage & hiding power', 'Emulsion for ceilings & walls'],
    uses: [
      'Undercoat under Cloud Paints decorative top coats',
      'Economical finishing of ceilings and walls',
      'High-coverage interior, exterior and masonry surfaces',
    ],
    surfaces: ['Concrete', 'Plaster', 'Masonry', 'Gypsum', 'Previously painted surfaces'],
    application: {
      prep: 'Surfaces must first be thoroughly cleaned free from all dust and grease objects for a better result.',
      new_surface: 'It is advisable to prime the surface before using the top coat of Cloud Paints Silk Vinyl Emulsion and must be sanded properly for an absolute acceptable finish.',
      previously_painted: 'The surface must be sanded properly for an absolute acceptable finish before using the top coat of Cloud Paints Silk Vinyl Emulsion.',
      method: 'Stir well before use. Cloud Paints SuperMatt Undercoat can be applied by brush, roller or spray equipment. It should not be thinned beyond 25% of water. An interval of 2–3 hrs is recommended for re-coating and gives an absolute good result.',
      cleanup: 'Clean tools with water and rinse properly for the next use.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based · no harmful smell',
      storage: 'Store in a cool, dry place, out of direct sunlight. Keep lid tightly closed.',
      first_aid: 'In case of eye contact, rinse with plenty of clean water. If skin contact, wash with soap and water. Seek medical advice if irritation persists.',
      disposal: 'Do not empty into drains or watercourses. Dispose of in accordance with local regulations.',
    },
    datasheet: 'datasheets/supermatt.pdf',
    pairs_with: ['vinyl-matt', 'silk-vinyl', 'weatherguard'],
  },

  /* ------------------------------------------------------------
     5. WEATHERGUARD 
     Label verbatim source: WEATHERGUARD 4LTS REV SEP.pdf
  ------------------------------------------------------------ */
  {
    slug: 'weatherguard',
    surface_tags: ['exterior'],
    name: 'Weatherguard with Silicone',
    tagline: 'Beautiful Today. Protected for Years.',
    cat: 'exterior-wall',
    cat_label: 'Exterior Wall Paint',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-weatherguard',
    primary: '#8b1e2c',
    accent: '#d92843',
    image: 'images/buckets/WEATHERGUARD 4LTS REV SEP.jpg',
    sizes: ['20L', '4L', '1L'],
    short: 'Advanced silicone technology and premium acrylic performance — a finish that repels water, resists harsh weather, and keeps colours looking vibrant. Built to protect, designed to impress.',
    full: 'Cloud Paints Weatherguard with Silicone is engineered for every climate. Whether exposed to intense sunshine, heavy rain, or changing temperatures, it forms a durable protective barrier that helps maintain the beauty of your home year after year. The advanced silicone technology delivers superior water repellency, while the anti-carbonation formulation and excellent UV resistance keep colours vivid and reduce fading. From elegant family homes to landmark commercial projects, Weatherguard delivers dependable protection with a premium finish.',
    features: [
      '🛡️ Advanced silicone protection for superior water repellency',
      '☀️ Excellent UV resistance to reduce fading',
      '🌧️ Weatherproof performance against rain and moisture',
      '🎨 Long-lasting colour retention',
      '✨ Smooth, premium exterior finish',
      '🏠 Helps protect masonry surfaces',
      '🧼 Low dirt pick-up for a cleaner-looking façade',
      '🌱 Low odour · environmentally considerate formula',
      'Anti-carbonation · resists fungus and algae growth',
      'Covers hairline cracks · hides minor imperfections',
    ],
    specs: {
      'Coverage':   '10–12 m² per litre',
      'Touch dry':  '1 hour',
      'Recoat':     '3–4 hours',
      'Finish':     'Smooth matt with silicone',
      'Thinning':   '10–15% clean water (first coat only)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Clean water',
    },
    claims: [
      'Beautiful Today. Protected for Years.',
      'Built to Protect. Designed to Impress.',
      'A home\'s exterior is the first impression it makes — Weatherguard keeps it fresh.',
    ],
    uses: [
      'Luxury homes and villas',
      'Contemporary residences',
      'Apartments and townhouses',
      'Commercial buildings',
      'Hotels and resorts',
      'Schools and institutions',
      'Humid and coastal areas — Mombasa, Kilifi, Malindi, Diani',
    ],
    colour_combos: [
      { name: 'Arctic White',  trim: 'Charcoal Grey',   note: 'Modern architectural look' },
      { name: 'Warm Ivory',    trim: 'Stone Grey',      note: 'Timeless elegance' },
      { name: 'Sand Beige',    trim: 'Dark Bronze',     note: 'Natural, earthy finish' },
      { name: 'Soft Grey',     trim: 'Pure White',      note: 'Sophisticated contemporary style' },
      { name: 'Cream Walls',   trim: 'Olive Green',     note: 'Tropical aesthetic' },
    ],
    design_tips: [
      'Prepare and repair the surface — sound substrate is half the job.',
      'Apply a quality exterior primer before the topcoat.',
      'Finish with two coats of Weatherguard with Silicone for maximum protection and a uniform finish.',
    ],
    surfaces: ['Concrete', 'Plaster', 'Masonry', 'Cement render', 'Previously painted exteriors'],
    application: {
      prep: 'Surfaces must first be thoroughly cleaned free from all dust and grease objects for a better result.',
      new_surface: 'Cloud Paints Weather Guard is advisable to prime the surface before using the top coat of Cloud Paints Weather Guard and must be sanded properly for an absolute acceptable finish.',
      previously_painted: 'The surface must be sanded properly for an absolute acceptable finish before using the top coat of Cloud Paints Weather Guard.',
      method: 'Stir well before use. Cloud Paints Weather Guard Emulsion can be applied by brush, roller or spray equipment. For first coat on porous surfaces, ease of application and for spray application, paint can be thinned with 10–15% clean water. Avoid over-thinning.',
      cleanup: 'Clean equipment with clean water.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based',
      storage: 'Store in a cool, dry place, out of direct sunlight. Keep lid tightly closed.',
      first_aid: 'In case of eye contact, rinse with plenty of clean water. If skin contact, wash with soap and water. Seek medical advice if irritation persists.',
      disposal: 'Do not empty into drains or watercourses. Dispose of in accordance with local regulations.',
    },
    datasheet: 'datasheets/weatherguard.pdf',
    pairs_with: ['rocketex', 'supermatt', 'roof-paint'],
  },

  /* ------------------------------------------------------------
     6. ROCKETEX (RockTEX / RuffTEX) 
     Label verbatim source: Cloudsent Paint Label - 2020 - RockTex - FINAL.pdf
  ------------------------------------------------------------ */
  {
    slug: 'rocketex',
    surface_tags: ['exterior'],
    name: 'Rocketex Wallmaster',
    tagline: 'Polymer textured paint · Extra tough',
    cat: 'exterior-wall',
    cat_label: 'Exterior Wall Paint',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-rocketex',
    primary: '#1f2547',
    accent: '#3b5bdb',
    image: 'images/buckets/ROCKETEX 30KG.jpg',
    sizes: ['30kg', '5kg'],
    short: 'Super-premium 100% acrylic textured coating. Trowel or roller applied for multi-directional textures and designer finishes. 15-year all-weather protection warranty. Over 5,000 colour shades.',
    full: 'Cloud RockTEX Texture is a super-premium Acrylic Emulsion based on an acrylic resin for a textured finish with guaranteed high performance, formulated to provide multi-directional textures (creation of designer texture and designs). It comes in more than 5,000 exuberant colours on any exterior & interior cementitious surface. A flexible acrylic texture applied directly from the bucket. Formulated with special materials such as tough stone crystals that give it unparalleled toughness and durability, making it a perfect choice for exterior painting and also interiors.',
    features: [
      'Stylish multiple textured effects',
      'Light rock finish',
      'Trowel or roller applied',
      'Excellent adhesion to wall',
      'Anti-carbonation formula',
      '15-year all-weather warranty',
    ],
    specs: {
      'Coverage':   '10–11 m² per 30 kg @ 1–1.5 mm film',
      'Touch dry':  '4 hours',
      'Hard dry':   '24 hours',
      'Max hardness': '7 days',
      'Finish':     'Matt high-build textured',
      'Thinning':   'Supplied ready-to-use — do not thin',
      'Application': 'Stainless-steel trowel · Roller',
      'Cleaner':    'Clean water',
    },
    claims: [
      'Strong & tuff.',
      'Stylish multiple textured effects.',
      '15-year all-weather protection warranty.',
      'Over 5,000 shades to choose from.',
    ],
    uses: [
      'Exterior feature walls and villas',
      'Interior accent walls with designer textures',
      'Hiding surface imperfections on older buildings',
      'Hospitality and commercial façades',
    ],
    surfaces: ['Plaster', 'Cement rendering', 'Block work', 'Cement', 'Stone', 'Bag-washed concrete', 'Fair-faced concrete', 'Timber', 'Glass', 'Aluminium'],
    application: {
      prep: 'All surfaces must be thoroughly cleaned and free of all dirt, loose and flaking paint. Efflorescence or mould must be treated before application. New concrete, mortar or cement render must be allowed to cure for 4 to 8 weeks depending on concrete thickness and drying conditions. Fill holes with grouting cement. Wash down with water using a stiff brush to remove all loose material.',
      new_surface: 'On porous surfaces, apply a priming coat thinned with water (4 parts RockTEX Texture : 1 part water) to condition the surface and aid application of additional coats.',
      previously_painted: 'Remove all loose and flaking paint. Clean thoroughly. Treat any efflorescence or mould before re-coating.',
      method: 'Apply using a stainless-steel trowel. For finishing and texturing, a special finishing tool (stainless-steel trowel, plastic trowel or comb) is required depending upon the textured finish (circular, horizontal, vertical). STIR THOROUGHLY BEFORE USE. Best applied when wet.',
      cleanup: 'Clean tools with water immediately after use.',
    },
    safety: {
      lead: 'No added lead, mercury or chromium compounds',
      voc: 'Water-based · low VOC',
      storage: 'Store container in upright position, with lid tightly closed, in a cool, dry place.',
      first_aid: 'Keep out of the reach of children and away from food, drink and animal feed. May be harmful if swallowed. In case of ingestion seek immediate medical attention.',
      disposal: 'Do not pour leftover paint down the drains or in water-courses. Contain spillage using sand or earth.',
      precautions: ['Protect from rain for 24 hours after application.'],
    },
    datasheet: 'datasheets/rocketex.pdf',
    pairs_with: ['weatherguard', 'supermatt'],
  },

  /* ------------------------------------------------------------
     7. GLOSS ENAMEL PAINT 
     Label verbatim source: GLOSS ENAMEL PAINT 4LTRS 1.pdf
  ------------------------------------------------------------ */
  {
    slug: 'gloss-enamel',
    surface_tags: ['wood', 'metal'],
    name: 'Gloss Enamel',
    tagline: 'Tough high-sheen finish for wood & metal',
    cat: 'enamel',
    cat_label: 'Gloss Enamel - Wood & Metal',
    grade: 'Economy',
    kebs: '',
    brandClass: 'brand-gloss',
    primary: '#0f1f5c',
    accent: '#1e3a8a',
    image: 'images/buckets/GLOSS ENAMEL 4L.jpg',
    sizes: ['4L', '1L'],
    short: 'Oil-based gloss enamel for interior and exterior wood, metal and plaster. Tough, durable high-sheen finish with good knock and scuff resistance, excellent hiding power and UV fastness.',
    full: 'Cloud Enamel Paint is a high VOC content gloss enamel finish and washable oil-based product, suitable for interior and exterior use. Gives a tough, durable high-sheen finish on wood, metal and plaster providing good resistance to knocking and scuffing. Can be applied over most previously painted surfaces without an undercoat. On new surfaces apply over the top of a suitable primer and undercoat. A fast-drying enamel manufactured to provide a strong paint film with good chemical resistance; a selection of high-quality pigments further enhances the properties by providing improved weathering resistance and UV light fastness of the coating.',
    features: [
      'Excellent durability',
      'Fully washable',
      'Stain & dirt resistant',
      'Good hiding power',
      'Interior & exterior use',
      'Fast drying',
    ],
    specs: {
      'Coverage':   '13 m² per litre (over Cloud Universal Undercoat on smooth surface)',
      'Touch dry':  '40 minutes',
      'Hard dry':   '16 hours',
      'Recoat':     '16 hours',
      'Finish':     'High gloss',
      'Thinning':   'Cloud White Spirit (if required)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Industrial Brush White Spirit (1L or 5L)',
    },
    claims: [
      'Excellent durability · Fully washable',
      'Stain & dirt resistant · Good hiding power',
      'Tough, durable high-sheen finish on wood, metal and plaster.',
    ],
    uses: [
      'New and previously painted cement plaster, asbestos/fibre cement',
      'Primed metal and wooden surfaces',
      'Steel door and window frames, interior walls, kitchen and bathroom walls, gates, steel fencing',
      'Garden tools, plaques and models',
    ],
    surfaces: ['Wood', 'Metal', 'Plaster', 'Cement', 'Asbestos/fibre cement', 'Previously painted enamel surfaces'],
    application: {
      prep: 'Ensure surface is clean, dry and free from dust, grease and flaking paint.',
      new_surface: 'Apply over the top of a suitable primer and undercoat. For bare wood and timber, we recommend applying a suitable wood primer such as Penetrating Wood Primer.',
      previously_painted: 'Can be applied over most previously painted surfaces without an undercoat. Sand glossy surfaces lightly to provide a key.',
      method: 'Use rollers, brush or spray to apply. Stir well before use.',
      cleanup: 'Clean paint brushes, rollers and spray equipment with Cloud Industrial Brush White Spirit (1L or 5L).',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'High VOC — oil-based · use in well-ventilated areas',
      storage: 'Store in suitable natural weather conditions. Exposure to direct sun or extreme cold may affect quality and shelf life. Keep container tightly closed.',
      first_aid: 'Avoid contact with the eye. If this occurs, wash with water and follow doctor\'s instructions. Keep away from the reach of children. Do not use after unpacking in food preservation.',
      disposal: 'The product is free of environmental pollutants. Dispose of leftover product in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: 'datasheets/gloss-enamel.pdf',
    pairs_with: ['universal-undercoat', 'metal-primer', 'super-gloss', 'white-spirit'],
  },

  /* ------------------------------------------------------------
     8. SUPER GLOSS 
     Label verbatim source: Cloud Paints Combined 2.pdf
  ------------------------------------------------------------ */
  {
    slug: 'super-gloss',
    surface_tags: ['wood', 'metal'],
    name: 'Super Gloss',
    tagline: 'Quick-dry high gloss for wood & metal',
    cat: 'enamel',
    cat_label: 'Trade Gloss Enamel',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-gloss',
    primary: '#1e3a8a',
    accent: '#3b5bdb',
    image: 'images/buckets/SUPER GLOSS 4L.jpg',
    sizes: ['20L', '4L', '1L'],
    short: 'Superior alkyd-based high gloss with excellent flow, giving surfaces a tough, durable high-gloss finish. Touch-dry in 1 hour. Formulated for tropical coastal weather conditions.',
    full: 'Cloud Super High Gloss is an alkyd-based superior Solvent-based formulation which offers excellent flow, giving surfaces a tough, durable high gloss finish. Cloud Super Gloss is formulated to offer maximum durability in extreme tropical coastal weather conditions. Self-undercoating, wipeable, non-yellowing. Suitable for use on plaster, wallboards, brickwork and stonework etc., over the appropriate primer and undercoat.',
    features: [
      'Low odour · convenient & pleasant to use',
      'High sheen · UV resistant',
      'Quick dry · touch dry in 1 hour',
      'Fully washable · long-lasting protection',
      'Low VOC',
      'No added lead or mercury',
    ],
    specs: {
      'Coverage':   '13–15 m² per litre (over Cloud Universal Undercoat on smooth surface)',
      'Touch dry':  '1 hour',
      'Through dry': '4 hours',
      'Recoat':     '16 hours',
      'Finish':     'Full high gloss',
      'Thinning':   'White Spirit (to required viscosity for spray)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Cloud White Spirit',
    },
    claims: [
      'High gloss · Quick dry · Lasting protection',
      'For wood & metal.',
      'Touch dry in 1 hour.',
    ],
    uses: [
      'Doors, cabinets, trims, furniture and exterior wood work',
      'Interior and exterior wood and metal',
      'Radiators',
      'Plaster, wallboards, brickwork and stonework',
    ],
    surfaces: ['Wood', 'Metal', 'Plaster', 'Wallboards', 'Brickwork', 'Stonework'],
    application: {
      prep: 'Ensure surface is clean, dry and free from dust, grease and flaking paint. Lightly sand glossy surfaces.',
      new_surface: 'Apply over the appropriate primer and undercoat (Cloud Universal Undercoat or Metal Primer as appropriate).',
      previously_painted: 'Sand to provide a key. Spot-prime bare areas before top coating.',
      method: 'Use soft brush or roller for application. Thin to the required viscosity with White Spirit for spray. Avoid over-thinning. Stir well before use.',
      cleanup: 'After use, remove as much paint as possible from brushes before cleaning with Cloud White Spirit.',
    },
    safety: {
      lead: 'No added lead or mercury',
      voc: 'Low VOC (for an oil-based gloss) · use in well-ventilated areas',
      storage: 'Store in suitable natural weather conditions. Product exposure to direct sun or extreme cold may affect quality and shelf life. Keep lid tightly closed.',
      first_aid: 'Avoid contact with the eye. If this occurs, wash with water and follow doctor\'s instructions. Keep away from the reach of children. Do not use after unpacking in food preservation.',
      disposal: 'The product is free of environmental pollutants. Dispose of in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: 'datasheets/super-gloss.pdf',
    pairs_with: ['universal-undercoat', 'metal-primer', 'white-spirit'],
  },

  /* ------------------------------------------------------------
     9. ROOF PAINT 
     Label verbatim source: ROOF PAINT 4L.pdf
  ------------------------------------------------------------ */
  {
    slug: 'roof-paint',
    surface_tags: ['exterior', 'metal'],
    name: 'Roof Paint',
    tagline: 'Quality durable flexible roof coating',
    cat: 'roof',
    cat_label: 'Roof Paint',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-roof',
    primary: '#8b1e2c',
    accent: '#d92843',
    image: 'images/buckets/ROOF PAINT 4L.jpg',
    sizes: ['4L', '1L'],
    short: 'High-quality durable flexible coating for galvanised roofs and exposed steelwork. Unique formulation withstands extreme weather variations. Available in Green, Red Oxide, Granite Grey and 17 special colours.',
    full: 'Cloud Roof Paint is a high-quality durable, flexible, beautiful coating for the protection of galvanised roofs and exposed steelwork. Manufactured from the finest light-fast pigments ground in a flexible medium paint product. Its unique formulation provides a flexible coating to withstand extreme variations in various weather conditions. It has excellent hiding power. One finishing coat is normally sufficient for redecoration work.',
    features: [
      'Quality durable',
      'Flexible coating',
      'Beautiful semi-gloss finish',
      'Excellent hiding power',
      'Weather resistant',
      'For galvanised roofs & steelwork',
    ],
    specs: {
      'Coverage':   '10–12 m² per litre (on smooth, non-porous surfaces)',
      'Recoat':     '16 hours',
      'Finish':     'Semi-gloss',
      'Thinning':   'Cloud White Spirit (if required for spray)',
      'Application': 'Brush · Spray (roller on flat surfaces)',
      'Cleaner':    'Cloud White Spirit',
      'Colours':    'Green · Red Oxide · Granite Grey (+17 on request)',
    },
    claims: ['Quality durable', 'Flexible', 'Beautiful coating'],
    uses: [
      'Galvanised (G.C.I.) roofing sheets',
      'Exposed steelwork',
      'Re-decorating previously painted roofs',
      'Industrial and residential metal roofs',
    ],
    surfaces: ['Galvanised sheets (G.C.I.)', 'Weathered galvanised metal', 'Previously painted roof sheets', 'Exposed steelwork'],
    application: {
      prep: 'Prepare surface. Clean thoroughly. Remove rust, dust and loose material.',
      new_surface: 'For new (unweathered) galvanised surfaces / G.C.I. sheets — degrease and prepare surface. Cloud Zinc Phosphate single coat can be applied as primer.',
      previously_painted: 'Prepare surface. Patch-prime with appropriate primer on bare metal surfaces only. Apply 1–2 coats of Cloud Roof Paint.',
      method: 'Apply by brush or spray on corrugated surfaces. Roller can be used on flat surfaces. Stir well before use. Avoid over-thinning — opacity will be affected.',
      cleanup: 'Use Cloud Standard Thinner or Cloud White Spirit for cleaning equipment.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Oil-based · use in well-ventilated areas',
      storage: 'Store in a cool, dry place. Keep lid tightly closed.',
      first_aid: 'Avoid contact with the eye. If this occurs, wash with water and follow doctor\'s instructions.',
      disposal: 'Dispose of in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: 'datasheets/roof-paint.pdf',
    pairs_with: ['metal-primer', 'weatherguard', 'white-spirit'],
  },

  /* ------------------------------------------------------------
     10. ROAD MARKING PAINT 
     Label verbatim source: ROOF PAINT 4L.pdf (combined document)
  ------------------------------------------------------------ */
  {
    slug: 'road-marking',
    surface_tags: ['exterior'],
    name: 'Road Marking Paint',
    tagline: 'High-opacity fast-drying road marking',
    cat: 'road',
    cat_label: 'Road & Line Marking Paint',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-floor',
    primary: '#1a202c',
    accent: '#4a5568',
    image: 'images/buckets/ROAD MARKING 4L.jpg',
    sizes: ['20L', '4L', '1L'],
    short: 'Single-pack fast-drying road marking paint on a durable alkyd-modified chlorinated rubber resin. Clean high-visibility lines on concrete and bitumen. White, yellow and black.',
    full: 'Cloud Road Marking Paint is a single pack fast drying coating based on a durable alkyd-modified chlorinated rubber resin. It is most suitable for concrete and bitumen surfaces without bleeding or discolouration, providing clean lines of high visibility. Manufactured from high-quality pigments and a mixture of high-quality resins for added durability. Advantages: good flexibility, excellent adhesion and quick drying.',
    features: [
      'Hardwearing',
      'Excellent adhesion',
      'High opacity',
      'Quick drying',
      'Solvent based',
      'For interior & exterior use',
    ],
    specs: {
      'Coverage':   '2.5–3 m² per litre @ 175µm WFT (per KEBS spec)',
      'Touch dry':  '4–10 minutes',
      'Finish':     'Matt',
      'Thinning':   'Cloud Road Marking Thinner · avoid over-thinning',
      'Application': 'Brush · Spraying machine',
      'Cleaner':    'Cloud Road Marking Paint Thinner',
      'Colours':    'White · Yellow · Black',
    },
    claims: [
      'Hardwearing · Excellent adhesion · High opacity',
      'Can be used on bitumen surfaces, marking of parking areas and sign writing on roads.',
    ],
    uses: [
      'Highways and urban roads',
      'Parking lot line marking',
      'Warehouse and factory floor lines',
      'Sign writing on bitumen and concrete',
    ],
    surfaces: ['Concrete', 'Bitumen', 'Asphalt'],
    application: {
      prep: 'Use dry, clean brush. Remove all dirt from the surface and remove any loose chippings. Ensure the surface is perfectly dry at the time of painting.',
      new_surface: 'Apply directly — no primer required on clean concrete or bitumen.',
      previously_painted: 'Remove loose paint. Clean surface thoroughly before re-coating.',
      method: 'Apply generously by brush, 1 coat of Cloud Road Marking Paint. Avoid excessive over-brushing. For machine application, thin to the required spray viscosity with Cloud Roadline Thinner. Stir well before use.',
      cleanup: 'Clean equipment immediately with Cloud Road Marking Paint Thinner.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Solvent-based · use in well-ventilated areas',
      storage: 'Store in a cool, dry place. Keep lid tightly closed.',
      first_aid: 'Avoid contact with eyes and skin. In case of eye contact, wash with water and seek medical advice.',
      disposal: 'Dispose of in accordance with local regulations. Contain spillage with sand or earth.',
      flammable: 'Flammable — keep away from flames and sources of ignition.',
    },
    datasheet: 'datasheets/road-marking.pdf',
    pairs_with: ['standard-thinner', 'floor-paint'],
  },

  /* ------------------------------------------------------------
     11. METAL PRIMER  — no individual label PDF
     Industry-standard alkyd anti-corrosive primer.
  ------------------------------------------------------------ */
  {
    slug: 'metal-primer',
    surface_tags: ['metal'],
    name: 'Metal Primer',
    tagline: 'Anti-corrosive primer for ferrous metal',
    cat: 'primer',
    cat_label: 'Metal Primer',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-undercoat',
    primary: '#4a5568',
    accent: '#718096',
    image: 'images/buckets/metal-primer.jpg',
    sizes: ['5L', '1L'],
    short: 'Alkyd-based anti-corrosive primer for ferrous metal surfaces. Creates a tight, durable bond with the substrate and acts as the perfect foundation for Cloud Paints gloss enamel top coats.',
    full: 'Cloud Paints Metal Primer is an alkyd-based anti-corrosive primer formulated specifically for ferrous metal surfaces. Creates a tight, durable bond with the substrate and acts as the perfect undercoat foundation for any of our gloss enamel or industrial top coats. Inhibits rust and extends the service life of exposed steelwork.',
    features: [
      'Anti-corrosive',
      'Excellent adhesion to steel',
      'Rust prevention',
      'Fast drying',
      'For interior & exterior metal',
      'Easy to apply',
    ],
    specs: {
      'Coverage':   '12 m² per litre (on smooth surface)',
      'Touch dry':  '1 hour',
      'Recoat':     '4 hours',
      'Finish':     'Matt primer',
      'Thinning':   'Cloud White Spirit (if required)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Cloud White Spirit',
    },
    claims: ['Anti-corrosive', 'Excellent adhesion', 'Rust prevention'],
    uses: [
      'Steel gates, grilles and security bars',
      'Steel fencing and balustrades',
      'Iron sheets and metal furniture',
      'Undercoat before Cloud Gloss Enamel',
    ],
    surfaces: ['Mild steel', 'Iron', 'Galvanised metal', 'Ferrous metal surfaces'],
    application: {
      prep: 'Remove all rust, loose paint, grease and dirt. Wire-brush or sand to bright metal where possible. Ensure surface is dry before painting.',
      new_surface: 'Apply directly to clean, dry ferrous metal. One full coat is normally sufficient before top-coating.',
      previously_painted: 'Spot-prime bare areas only. Lightly sand sound paintwork to provide a key.',
      method: 'Apply by brush, roller or spray. Stir well before use. Avoid over-thinning.',
      cleanup: 'Clean equipment with Cloud White Spirit immediately after use.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Solvent-based · use in well-ventilated areas',
      storage: 'Store in a cool, dry place. Keep lid tightly closed.',
      first_aid: 'Avoid contact with eyes and skin. In case of eye contact, wash with water and seek medical advice.',
      disposal: 'Dispose of in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: '',
    pairs_with: ['gloss-enamel', 'super-gloss', 'white-spirit'],
  },

  /* ------------------------------------------------------------
     12. UNIVERSAL UNDERCOAT  — no individual label PDF
     Referenced as "Cloud Universal Undercoat" on Gloss Enamel
     and Super Gloss labels.
  ------------------------------------------------------------ */
  {
    slug: 'universal-undercoat',
    surface_tags: ['wood', 'metal', 'cement'],
    name: 'Universal Undercoat',
    tagline: 'Smooth foundation for any top coat',
    cat: 'primer',
    cat_label: 'Universal Undercoat',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-undercoat',
    primary: '#718096',
    accent: '#a0aec0',
    image: 'images/buckets/universal-undercoat.jpg',
    sizes: ['4L', '1L'],
    short: 'All-purpose solvent-based undercoat for interior and exterior wood, metal and primed masonry. The standard base coat for Cloud Gloss Enamel and Super Gloss.',
    full: 'Cloud Universal Undercoat is the companion product to Cloud Gloss Enamel and Super Gloss — a solvent-based alkyd undercoat providing excellent adhesion, fill and a uniform base for any oil-based top coat. Saves time, promotes even sheen in the topcoat and ensures truer final colour. Suitable for wood, primed metal and primed masonry.',
    features: [
      'Excellent adhesion',
      'Uniform smooth base',
      'Saves topcoat',
      'For wood, metal & masonry',
      'Quick drying',
      'Easy to apply',
    ],
    specs: {
      'Coverage':   '12–14 m² per litre',
      'Touch dry':  '1 hour',
      'Recoat':     '4 hours',
      'Finish':     'Matt — designed to be over-coated',
      'Thinning':   'Cloud White Spirit (if required)',
      'Application': 'Brush · Roller · Spray',
      'Cleaner':    'Cloud White Spirit',
    },
    claims: ['Excellent adhesion', 'Uniform smooth base', 'Saves topcoat'],
    uses: [
      'Base coat before Cloud Gloss Enamel or Super Gloss',
      'Doors, window frames, furniture',
      'Primed metal gates and grilles',
      'Previously painted wood requiring a fresh base',
    ],
    surfaces: ['Wood', 'Primed metal', 'Previously painted surfaces', 'Primed masonry'],
    application: {
      prep: 'Surface must be clean, dry and free of dust, grease and flaking paint. Lightly sand glossy surfaces to provide a key.',
      new_surface: 'Apply directly to clean, sound wood. For bare metal, apply Cloud Metal Primer first.',
      previously_painted: 'Lightly sand and clean. One coat of undercoat is normally sufficient before top-coating.',
      method: 'Apply by brush, roller or spray. Stir well before use.',
      cleanup: 'Clean tools with Cloud White Spirit immediately after use.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Solvent-based · use in well-ventilated areas',
      storage: 'Store in a cool, dry place. Keep lid tightly closed.',
      first_aid: 'Avoid contact with eyes and skin. In case of eye contact, wash with water and seek medical advice.',
      disposal: 'Dispose of in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: '',
    pairs_with: ['gloss-enamel', 'super-gloss', 'metal-primer'],
  },

  /* ------------------------------------------------------------
     13. CLEAR VARNISH 
     Label verbatim source: Cloud Paints Combined 1.pdf
  ------------------------------------------------------------ */
  {
    slug: 'clear-varnish',
    surface_tags: ['wood'],
    name: 'Clear Varnish',
    tagline: 'Superior scratch-resistant clear gloss',
    cat: 'wood',
    cat_label: 'Wood Varnish - Clear Gloss',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-varnish',
    primary: '#92400e',
    accent: '#d69e2e',
    image: 'images/buckets/CLEAR VARNISH 4L.jpg',
    sizes: ['20L', '4L', '1L'],
    short: 'Quick-drying multipurpose clear varnish for interior woodwork. Blend of modified polyurethane alkyd resin and hardening agent that preserves the natural beauty of timber.',
    full: 'Cloud Multipurpose Clear Varnish is a quick-drying clear varnish formulated to produce a tough, gloss finish on interior woodwork. Recommended for use as a furniture finish and for general application on new or sanded door panels and frames, counters, timber pelmets, skirting boards, wall partitions etc. Manufactured from a blend of high-quality oil-modified polyurethane alkyd resin and a special hardening resin that maintains the natural beauty of the timber. Retains the natural beauty of timber · High spreading capacity and quick drying · Tough, hard-wearing abrasion-resistant clear gloss finish.',
    features: [
      'Superior scratch resistant',
      'Maximum durability',
      'Fast dry time',
      'High spreading capacity',
      'Retains natural beauty of timber',
      'Abrasion resistant',
    ],
    specs: {
      'Coverage':   '12–15 m² per litre (on smooth, non-porous surfaces)',
      'Touch dry':  '3–4 hours',
      'Recoat':     '12–16 hours',
      'Finish':     'Clear gloss',
      'Thinning':   'Cloud White Spirit',
      'Application': 'Brush (working well into grain)',
      'Cleaner':    'Cloud White Spirit',
      'Coats':      '2–3 recommended',
    },
    claims: ['Superior scratch resistant', 'Maximum durability', 'Fast dry time'],
    uses: [
      'Doors, trim, furniture and joinery',
      'Counters and timber pelmets',
      'Skirting boards and wall partitions',
      'Interior woodwork requiring a clear protective finish',
    ],
    surfaces: ['Interior woodwork', 'New timber', 'Previously varnished wood (properly prepared)'],
    application: {
      prep: 'Ensure wood is clean, dust-free and defective or poorly adhering material removed. Rub down with abrasive paper and dust off.',
      new_surface: 'Apply a minimum of 3 coats Cloud Multipurpose Clear Varnish. On new bare timber, the first coat should be thinned to ease brushing consistency using Cloud White Spirit. Subsequent coats can be thinned if necessary.',
      previously_painted: 'For previously varnished woodwork — unsound timber: remove all old and damaged varnish down to bare surface. If necessary, use Cloud Paint and Varnish Remover and/or mechanical sanding equipment. Prepare surface as for new timber. Apply 3 coats Cloud Multipurpose Clear Varnish.',
      method: 'By brush, working well into the surface to get good penetration and adhesion on wood. Not recommended for floors. Finish high gloss — the latter is not recommended for use on floors.',
      cleanup: 'Clean all equipment with Cloud White Spirit immediately after use.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Solvent-based · use in well-ventilated areas',
      storage: 'Store in dry conditions and protect from extreme temperatures.',
      first_aid: 'Do not empty into drains or watercourses. In case of accident, collect spillage using sand or earth. Do not empty into drains or watercourses. Avoid long-term adverse effects on the aquatic environment.',
      disposal: 'Dispose of any paint waste in accordance with the appropriate environment quality regulations.',
      flammable: 'Flammable — keep out of reach of children and away from sources of ignition. In case of fire use foam, CO₂ powder. Use in a well-ventilated area.',
    },
    datasheet: 'datasheets/clear-varnish.pdf',
    pairs_with: ['varnish-stain', 'white-spirit', 'turpentine'],
  },

  /* ------------------------------------------------------------
     14. VARNISH STAIN  — no individual label PDF
     Aligned with Clear Varnish technical profile.
  ------------------------------------------------------------ */
  {
    slug: 'varnish-stain',
    surface_tags: ['wood'],
    name: 'Varnish Stain',
    tagline: 'Tinted varnish for rich wood tones',
    cat: 'wood',
    cat_label: 'Wood Varnish - Tinted',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-varnish',
    primary: '#7c2d12',
    accent: '#c2410c',
    sizes: ['5L', '1L'],
    short: 'Tinted polyurethane alkyd varnish that stains and protects in a single coat. Deepens the natural look of wood with rich classic tones.',
    full: 'Cloud Paints Varnish Stain combines colour and protection in a single coat — adding rich, classic wood tones while sealing and protecting the surface. Built on the same polyurethane alkyd platform as Cloud Clear Varnish for hard-wearing, abrasion-resistant performance. Perfect for furniture, doors and trim where you want to deepen the natural look of wood without painting over the grain.',
    features: [
      'Stain + varnish in one coat',
      'Rich classic wood tones',
      'UV resistant',
      'Hard-wearing finish',
      'Retains wood grain visibility',
      'Long lasting',
    ],
    specs: {
      'Coverage':   '12–15 m² per litre',
      'Touch dry':  '3–4 hours',
      'Recoat':     '12–16 hours',
      'Finish':     'Tinted gloss',
      'Thinning':   'Cloud White Spirit',
      'Application': 'Brush · Cloth wipe',
      'Cleaner':    'Cloud White Spirit',
      'Colours':    'Mahogany · Walnut · Teak · Oak · Ebony',
    },
    claims: ['Stain + varnish in one coat', 'Rich classic wood tones', 'UV resistant'],
    uses: [
      'Furniture, doors and trim',
      'Interior joinery',
      'Enhancing natural wood grain with a warm tint',
      'Restoration of tired timber surfaces',
    ],
    surfaces: ['Interior woodwork', 'New timber', 'Previously stained wood (properly prepared)'],
    application: {
      prep: 'Clean wood thoroughly. Sand to remove defective material. Ensure surface is dust-free and dry.',
      new_surface: 'Apply 2–3 coats. First coat may be thinned slightly with Cloud White Spirit to aid penetration.',
      previously_painted: 'Remove old varnish or stain as needed. Sand to bare timber for best results.',
      method: 'Apply with brush, working well into the grain. Wipe excess with a lint-free cloth for an even tone. Stir well before use.',
      cleanup: 'Clean brushes with Cloud White Spirit immediately after use.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Solvent-based · use in well-ventilated areas',
      storage: 'Store in a cool, dry place. Keep lid tightly closed.',
      first_aid: 'Avoid contact with eyes and skin. In case of eye contact, wash with water and seek medical advice.',
      disposal: 'Dispose of in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: '',
    pairs_with: ['clear-varnish', 'white-spirit'],
  },

  /* ------------------------------------------------------------
     15. FLOOR PAINT  — no individual label PDF
     Industry-standard alkyd floor coating.
  ------------------------------------------------------------ */
  {
    slug: 'floor-paint',
    surface_tags: ['cement'],
    name: 'Floor Paint',
    tagline: 'Heavy-duty coating for industrial & residential floors',
    cat: 'floor',
    cat_label: 'Floor Paint',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-floor',
    primary: '#2d3748',
    accent: '#4a5568',
    sizes: ['4L', '1L'],
    short: 'Hard-wearing alkyd-based floor coating for concrete and wooden floors. Resists abrasion, chemicals, oil spills and heavy foot traffic. Built for warehouses, garages and residential floors.',
    full: 'Cloud Paints Floor Paint is a heavy-duty alkyd-based coating designed for concrete, wooden and industrial floors. Resists abrasion, chemicals, oil spills and heavy foot traffic. Ideal for warehouses, garages, workshops, factory floors and residential utility areas. Delivers a tough semi-gloss finish that is easy to clean and stands up to years of wear.',
    features: [
      'Heavy-duty coating',
      'Abrasion resistant',
      'Chemical & oil resistant',
      'For concrete & wood floors',
      'Industrial grade',
      'Easy to clean',
    ],
    specs: {
      'Coverage':   '10–12 m² per litre',
      'Touch dry':  '4 hours',
      'Recoat':     '12 hours',
      'Finish':     'Semi-gloss',
      'Thinning':   'Cloud White Spirit (if required)',
      'Application': 'Brush · Roller',
      'Cleaner':    'Cloud White Spirit',
      'Colours':    'Red Oxide · Green · Grey',
    },
    claims: ['Heavy-duty', 'Abrasion resistant', 'Chemical resistant'],
    uses: [
      'Warehouses and factory floors',
      'Garages and workshops',
      'Residential utility and balcony floors',
      'Line marking on industrial floors',
    ],
    surfaces: ['Concrete', 'Wood', 'Previously painted floor surfaces'],
    application: {
      prep: 'Concrete must be fully cured (minimum 28 days). Remove all dust, laitance, oil and grease. Acid-etch or mechanically abrade smooth concrete for adhesion.',
      new_surface: 'First coat may be thinned 10% with Cloud White Spirit to aid penetration on porous concrete. Follow with one to two full-strength coats.',
      previously_painted: 'Remove loose and flaking paint. Sand glossy areas to provide a key. Spot-prime bare concrete before over-coating.',
      method: 'Apply by brush or roller. Stir well before use. Allow full recoat interval between coats.',
      cleanup: 'Clean equipment with Cloud White Spirit immediately after use.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Solvent-based · use in well-ventilated areas',
      storage: 'Store in a cool, dry place. Keep lid tightly closed.',
      first_aid: 'Avoid contact with eyes and skin. In case of eye contact, wash with water and seek medical advice.',
      disposal: 'Dispose of in accordance with local regulations.',
      flammable: 'Keep away from flames and sources of ignition.',
    },
    datasheet: '',
    pairs_with: ['road-marking', 'standard-thinner'],
  },

  /* ------------------------------------------------------------
     16. WHITE SPIRIT  — no individual label PDF
     Paired with Gloss Enamel, Super Gloss, Clear Varnish.
  ------------------------------------------------------------ */
  {
    slug: 'white-spirit',
    surface_tags: [],
    name: 'White Spirit',
    tagline: 'High-purity thinner & equipment cleaner',
    cat: 'solvent',
    cat_label: 'Solvent - Thinner',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-thinner',
    primary: '#a0aec0',
    accent: '#cbd5e0',
    sizes: ['5L', '1L'],
    short: 'High-purity petroleum distillate for thinning oil-based paints, varnishes and enamels, and for cleaning brushes, rollers and spray equipment. Pairs with the Cloud Gloss and Varnish range.',
    full: 'Cloud Paints White Spirit is a high-purity petroleum distillate solvent for thinning oil-based paints, varnishes, enamels and stains. Also ideal for cleaning brushes, rollers and spray equipment, and for removing fresh paint splashes from hard surfaces. The standard cleanup solvent for the Cloud Gloss Enamel, Super Gloss, Roof Paint and Clear Varnish range.',
    features: [
      'High purity',
      'Paint thinner',
      'Tool cleaner',
      'Multi-purpose',
      'Professional grade',
      'Fast evaporating',
    ],
    specs: {
      'Use':         'Thinning · Equipment cleaning',
      'Type':        'Petroleum distillate',
      'Application': 'Mixing · Cleaning',
      'Flash point': '38°C (closed cup, typical)',
      'Storage':     'Cool, dry, well-ventilated place',
      'Cleaner':     'Not applicable (is the cleaner)',
    },
    claims: ['High purity', 'Paint thinner & tool cleaner', 'Professional grade'],
    uses: [
      'Thinning Cloud Gloss Enamel and Super Gloss',
      'Thinning Cloud Clear Varnish',
      'Cleaning brushes, rollers and spray equipment',
      'Removing fresh oil-based paint splashes',
    ],
    surfaces: [],
    application: {
      prep: 'Ensure work area is well ventilated and free of ignition sources.',
      new_surface: 'Not applicable — this is a solvent.',
      previously_painted: 'Not applicable — this is a solvent.',
      method: 'For thinning: add gradually to paint while stirring, to the required viscosity. For cleaning: immerse brushes and work solvent through bristles, then rinse and dry. Do not overthin paint.',
      cleanup: 'Dispose of used solvent responsibly — do not pour down drains.',
    },
    safety: {
      lead: 'Not applicable',
      voc: 'Petroleum distillate · flammable vapour',
      storage: 'Store in a cool, dry, well-ventilated place away from heat, flames and sparks. Keep container tightly closed.',
      first_aid: 'In case of eye contact, flush with plenty of water and seek medical attention. If swallowed, do NOT induce vomiting — seek immediate medical attention. If inhaled, move to fresh air.',
      disposal: 'Dispose of as flammable waste in accordance with local regulations. Do not pour into drains or watercourses.',
      flammable: 'Flammable liquid and vapour. DANGER — keep away from heat, flames, sparks, sunlight and static.',
    },
    datasheet: '',
    pairs_with: ['gloss-enamel', 'super-gloss', 'clear-varnish', 'roof-paint'],
  },

  /* ------------------------------------------------------------
     17. TURPENTINE 
     Label verbatim source: Cloud Paints Combined 5.pdf
  ------------------------------------------------------------ */
  {
    slug: 'turpentine',
    surface_tags: [],
    name: 'Turpentine',
    tagline: 'Pine-derived professional thinner',
    cat: 'solvent',
    cat_label: 'Solvent - Natural',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-thinner',
    primary: '#9ca3af',
    accent: '#d1d5db',
    image: 'images/buckets/TURPENTINE 5L.jpg',
    sizes: ['5L', '1L'],
    short: 'Professional-quality pine-tree-derived thinner for oil-based paints, enamels and varnishes. Multi-purpose — removes grease and grime, cleans brushes, dissolves polish components. Meets Federal Specification TT-T-801 C Type 1.',
    full: 'Turpentine Paint Remover is a pine tree-derived, professional-quality thinner for oil-based paints, enamels and varnishes. Cloud Turpentine is a multi-purpose product that can be used for many applications such as removing grease, grime from surfaces, as well as cleaning paintbrushes and paint rollers used with solvent-based paints such as Gloss Enamel, Primers and Varnishes etc. It can also be used for thinning down or spraying alkyd-based decorative paints. Can be used to dissolve polish components, e.g. Beeswax. Removes tar, grease and tree sap. Meets Federal Specification TT-T-801 C Type 1.',
    features: [
      'Pine tree-derived',
      'Professional quality',
      'Paint thinner for alkyd paints and varnishes',
      'Cleans brushes, rollers and spray equipment',
      'Suitable for spray applications',
      'Removes tar, grease and tree sap',
    ],
    specs: {
      'Use':         'Thinning · Cleaning · Grease removal',
      'Type':        'Natural pine-tree turpentine',
      'Application': 'Mixing · Cleaning · Spray thinning',
      'Standard':    'Federal Specification TT-T-801 C Type 1',
      'Storage':     'Cool, dry, well-ventilated place',
    },
    claims: [
      'Paint thinner for alkyd paints and varnishes.',
      'Cleans brushes, rollers and spray equipment.',
      'Meets Federal Specification TT-T-801 C Type 1.',
    ],
    uses: [
      'Thinning Cloud Gloss Enamel, Primers and Varnishes',
      'Cleaning brushes, rollers and spray equipment',
      'Dissolving polish components (e.g. Beeswax)',
      'Removing tar, grease and tree sap',
    ],
    surfaces: [],
    application: {
      prep: 'Use within well-ventilated areas. Keep away from heat, flames, sunlight, static and electrical sparks.',
      new_surface: 'Not applicable — this is a solvent.',
      previously_painted: 'Not applicable — this is a solvent.',
      method: 'For thinning: add gradually to paint while stirring. For cleaning: immerse brushes and work solvent through bristles, then rinse and dry.',
      cleanup: 'Secure cap tightly after use. Keep upright at all times.',
    },
    safety: {
      lead: 'Not applicable',
      voc: 'Natural hydrocarbon solvent · flammable vapour',
      storage: 'Store product in cool, well-ventilated area. Ensure cap is tightly sealed and packaging is secure and upright at all times. Secure product when transporting to prevent accidental spillage.',
      first_aid: 'If overexposed to fumes, move victim to fresh air and seek immediate medical attention. Use protective glasses — if contact with eyes occurs, flush open eyes with plenty of water and seek immediate medical attention. Causes mild skin irritation — wear protective gloves and avoid skin contact. Do not eat, drink or smoke when using. Take off contaminated clothing and wash before re-use. If swallowed, do NOT induce vomiting — seek immediate medical attention.',
      disposal: 'Dispose of container — do not use for any other purpose. Do not dispose of product into common waste system.',
      flammable: 'WARNING — Flammable liquid and vapour. DANGER: May be fatal if swallowed and enters airways. Toxic to aquatic life. Avoid release to the environment. Do not inhale vapour. In the event of a fire, use Carbon Dioxide Foam or Chemical Powder — NOT water.',
    },
    datasheet: 'datasheets/turpentine.pdf',
    pairs_with: ['gloss-enamel', 'clear-varnish', 'super-gloss'],
  },

  /* ------------------------------------------------------------
     18. STANDARD THINNER  — no individual label PDF
     Referenced on Roof Paint label as a cleaner option.
  ------------------------------------------------------------ */
  {
    slug: 'standard-thinner',
    surface_tags: [],
    name: 'Standard Thinner',
    tagline: 'Universal hydrocarbon thinner for the trade',
    cat: 'solvent',
    cat_label: 'Solvent - Universal',
    grade: 'Trade',
    kebs: '',
    brandClass: 'brand-thinner',
    primary: '#cbd5e0',
    accent: '#e2e8f0',
    sizes: ['5L', '1L'],
    short: 'All-round hydrocarbon-blend thinner for Cloud Paints enamels and undercoats. The contractor\'s choice for high-volume thinning and equipment cleaning across the Cloud solvent-based range.',
    full: 'Cloud Paints Standard Thinner is the universal, all-purpose thinner formulated for use with Cloud Paints enamel paints and undercoats. Compatible with the full Cloud Paints oil-based product range and ideal for cleanup of brushes, rollers and spray equipment. The cost-effective contractor-grade choice for high-volume work.',
    features: [
      'Universal compatibility',
      'Quick drying',
      'Compatible with Cloud oil-based range',
      'Multi-purpose',
      'Cost effective',
      'Professional grade',
    ],
    specs: {
      'Use':         'Thinning · Cleaning',
      'Type':        'Hydrocarbon blend',
      'Application': 'Mixing · Cleaning',
      'Storage':     'Cool, dry, well-ventilated place',
    },
    claims: ['Universal thinner for the Cloud oil-based range', 'Cost-effective contractor grade'],
    uses: [
      'Thinning Cloud Gloss Enamel and Super Gloss',
      'Thinning Cloud Roof Paint',
      'Cleaning brushes, rollers and spray equipment',
      'General cleanup on oil-based paint jobs',
    ],
    surfaces: [],
    application: {
      prep: 'Use within well-ventilated areas. Keep away from heat, flames and sparks.',
      new_surface: 'Not applicable — this is a solvent.',
      previously_painted: 'Not applicable — this is a solvent.',
      method: 'For thinning: add gradually to paint while stirring. For cleaning: immerse brushes and work solvent through bristles, then rinse and dry.',
      cleanup: 'Dispose of used solvent responsibly — do not pour down drains.',
    },
    safety: {
      lead: 'Not applicable',
      voc: 'Hydrocarbon solvent · flammable vapour',
      storage: 'Store in a cool, dry, well-ventilated place away from heat, flames and sparks. Keep container tightly closed.',
      first_aid: 'In case of eye contact, flush with plenty of water and seek medical attention. If swallowed, do NOT induce vomiting — seek immediate medical attention. If inhaled, move to fresh air.',
      disposal: 'Dispose of as flammable waste in accordance with local regulations. Do not pour into drains or watercourses.',
      flammable: 'Flammable liquid and vapour. Keep away from heat, flames and sparks.',
    },
    datasheet: '',
    pairs_with: ['gloss-enamel', 'super-gloss', 'roof-paint'],
  },

  /* ============================================================
     CLOUD PAINTS — DECORATIVE TEXTURE COLLECTION
     A curated ten-piece premium decorative range across five
     finish families (Modern Concrete, Decorative Pattern, Venetian
     Marble, Stone & Exterior Rock, Metallic & Shimmer). Applied by
     certified Cloud Paints decorative teams; specs reflect typical
     site practice.
  ============================================================ */

  /* 19. CLOUD STONE TEXTURE */
  {
    slug: 'cloud-stone-texture',
    surface_tags: ['cement', 'masonry'],
    name: 'Cloud Stone Texture',
    tagline: 'Hand-crafted stone-look finish',
    cat: 'texture',
    cat_label: 'Stone & Exterior Rock',
    grade: 'Decorative',
    kebs: '',
    brandClass: 'brand-cloud-stone',
    primary: '#7a6b5c',
    accent: '#c4a575',
    image: 'images/textures/cloud-stone-texture.jpg',
    sizes: ['25kg', '20kg'],
    short: 'A high-build decorative texture that hand-renders into a natural stone appearance — durable, weather-resistant and Kenyan-climate ready.',
    full: 'Cloud Stone Texture is a premium decorative coating from the Cloud Paints Texture Collection. Hand-trowelled and sculpted on site by certified applicators, it produces a tactile stone-look finish that protects boundary walls, gate pillars and façades against rain, dust and UV while adding architectural character.',
    features: [
      'Authentic stone-look finish',
      'Heavy-duty weather resistance',
      'Hides minor wall imperfections',
      'UV-stable colour system',
      'Suitable for boundary walls and pillars',
      'Applied by certified Cloud Paints teams',
    ],
    specs: {
      'Coverage':   '2–3 m² per kg (varies with profile depth)',
      'Touch dry':  '4–6 hours',
      'Recoat':     '24 hours',
      'Finish':     'Hand-sculpted stone',
      'Thinning':   'Ready for use · do not thin',
      'Application': 'Trowel · Sponge · Specialty tools',
      'Cleaner':    'Clean water (wet); chip off (cured)',
    },
    claims: ['Architectural stone, on any wall', 'Decorative + weather-shield in one pass'],
    uses: [
      'Exterior boundary walls and gate pillars',
      'Commercial building façades',
      'Garden feature walls and outdoor lounges',
      'Hospitality entrances and lobbies',
    ],
    surfaces: ['Plastered masonry', 'Concrete', 'Pre-primed exteriors'],
    application: {
      prep: 'Substrate must be sound, clean and free of laitance, mould or loose material. Prime with Cloud Paints Universal Undercoat where required.',
      new_surface: 'Allow new render to cure for at least 21 days. Apply a base coat of Weatherguard for adhesion, then build texture in two trowel passes.',
      previously_painted: 'Remove flaking material, wash down and key the surface. Prime worn areas before application.',
      method: 'Trowel apply at 2–3 mm build, then sculpt with sponge, comb or specialty tool while wet. Top coat with Weatherguard tinted to chosen shade for full protection.',
      cleanup: 'Wash tools with clean water before material cures.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based',
      storage: 'Store in cool, dry, shaded conditions. Keep tightly sealed.',
      first_aid: 'In case of eye contact, rinse with clean water. For skin contact, wash with soap and water.',
      disposal: 'Do not empty into drains. Allow residue to cure then dispose as construction waste.',
    },
    datasheet: '',
    pairs_with: ['weatherguard', 'cloud-rockshield-exterior', 'cloud-desert-stone'],
  },

  /* 20. CLOUD CONCRETE FINISH */
  {
    slug: 'cloud-concrete-finish',
    surface_tags: ['cement', 'gypsum'],
    name: 'Cloud Concrete Finish',
    tagline: 'Modern concrete-look texture',
    cat: 'texture',
    cat_label: 'Modern Concrete Texture',
    grade: 'Decorative',
    kebs: '',
    brandClass: 'brand-cloud-concrete',
    primary: '#7d7e80',
    accent: '#a8a6a1',
    image: 'images/textures/cloud-concrete-finish.jpg',
    sizes: ['20kg', '5kg'],
    short: 'A sophisticated raw-concrete look for modern apartments, TV walls and reception areas — masks minor wall imperfections while reading architectural and considered.',
    full: 'Cloud Concrete Finish is a fine-grain decorative coating that recreates the cool, matte surface of polished concrete. Ideal where the design language wants industrial calm without exposing actual concrete. Hand-applied by certified Cloud Paints teams over plastered or gypsum substrates.',
    features: [
      'Honest concrete-look finish',
      'Hides minor wall imperfections',
      'Low-sheen matte appearance',
      'Tintable to grey tones',
      'Interior · TV walls · reception',
      'Applied by certified Cloud Paints teams',
    ],
    specs: {
      'Coverage':   '4–5 m² per kg',
      'Touch dry':  '2–3 hours',
      'Recoat':     '12 hours',
      'Finish':     'Matte concrete',
      'Thinning':   'Ready for use',
      'Application': 'Trowel · Steel float',
      'Cleaner':    'Clean water',
    },
    claims: ['Architectural concrete, on any wall', 'Quietly modern'],
    uses: [
      'Modern apartment feature walls',
      'Industrial-style interiors and lofts',
      'TV walls and media rooms',
      'Office reception areas and showrooms',
    ],
    surfaces: ['Plaster', 'Gypsum board', 'Pre-primed concrete'],
    application: {
      prep: 'Sand and dust off. Prime with Cloud Paints Wall Sealer if substrate is porous.',
      new_surface: 'Allow plaster to cure 14+ days. Apply a thin tightening coat, then two trowel passes.',
      previously_painted: 'Sand to a key. Spot-prime any bare patches.',
      method: 'Apply with stainless trowel in thin overlapping passes. Steel-float lightly while damp for the polished look.',
      cleanup: 'Wash tools with clean water.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based',
      storage: 'Store in a cool, dry place.',
      first_aid: 'Rinse skin and eyes with clean water on contact.',
      disposal: 'Do not empty into drains.',
    },
    datasheet: '',
    pairs_with: ['supermatt', 'cloud-luxury-stucco', 'silk-vinyl'],
  },

  /* 21. CLOUD VELVET TEXTURE */
  {
    slug: 'cloud-velvet-texture',
    surface_tags: ['cement', 'gypsum'],
    name: 'Cloud Velvet Texture',
    tagline: 'Soft velvet-sheen accent finish',
    cat: 'texture',
    cat_label: 'Decorative Pattern',
    grade: 'Decorative',
    kebs: '',
    brandClass: 'brand-cloud-velvet',
    primary: '#6b5e7a',
    accent: '#c0a7b8',
    image: 'images/textures/cloud-velvet-texture.jpg',
    sizes: ['20L', '4L'],
    short: 'A subtly textured accent finish with a soft velvet sheen that catches light differently across the wall — designed for bedrooms and luxury lounges.',
    full: 'Cloud Velvet Texture is a smooth-bodied decorative paint that builds a low-relief brush pattern under a gentle velvet sheen. The result reads as quietly luxurious — pattern only emerges as the eye moves along the wall. Designed for accent walls in bedrooms, lounges and restaurants.',
    features: [
      'Soft velvet sheen',
      'Low-relief brush pattern',
      'Light-responsive surface',
      'Interior accent walls',
      'Tintable to deep moody shades',
      'Applied by certified Cloud Paints teams',
    ],
    specs: {
      'Coverage':   '8–10 m² per litre',
      'Touch dry':  '2 hours',
      'Recoat':     '6 hours',
      'Finish':     'Velvet sheen with subtle pattern',
      'Thinning':   '5% clean water (first coat only)',
      'Application': 'Brush · Specialty roller',
      'Cleaner':    'Clean water',
    },
    claims: ['Quietly luxurious', 'Pattern that reveals itself in light'],
    uses: [
      'Bedroom accent and headboard walls',
      'Luxury lounges and snugs',
      'Restaurant and bar interiors',
      'Boutique hotel corridors',
    ],
    surfaces: ['Plaster', 'Gypsum board', 'Previously-painted interiors'],
    application: {
      prep: 'Sand smooth and dust off. Patch and seal any holes.',
      new_surface: 'Prime with Cloud Paints Wall Sealer.',
      previously_painted: 'Sand sheen off existing paint, spot-prime bare patches.',
      method: 'Apply first coat as a flat base. Apply second coat with the specialty texture roller in long overlapping strokes — direction sets the pattern.',
      cleanup: 'Wash tools with clean water.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based',
      storage: 'Cool, dry place.',
      first_aid: 'Rinse with clean water on contact.',
      disposal: 'Do not empty into drains.',
    },
    datasheet: '',
    pairs_with: ['silk-vinyl', 'cloud-rustic-texture', 'cloud-metallic-illusion'],
  },

  /* 22. CLOUD METALLIC ILLUSION */
  {
    slug: 'cloud-metallic-illusion',
    surface_tags: ['gypsum', 'cement'],
    name: 'Cloud Metallic Illusion',
    tagline: 'Shimmering metallic accent',
    cat: 'texture',
    cat_label: 'Metallic & Shimmer',
    grade: 'Decorative',
    kebs: '',
    brandClass: 'brand-cloud-metallic',
    primary: '#9a7b3f',
    accent: '#e0c787',
    image: 'images/textures/cloud-metallic-illusion.jpg',
    sizes: ['4L', '1L'],
    short: 'A reflective metallic decorative finish that adds depth, shimmer and movement to a single feature wall — engineered for hotels, showrooms and luxury lounges.',
    full: 'Cloud Metallic Illusion suspends fine metallic particles in a water-based binder; trowel-application creates flowing strokes that catch light like brushed metal. Used sparingly on feature walls, it transforms an otherwise quiet interior into a piece of architecture.',
    features: [
      'Real metallic particle finish',
      'Light-reflective shimmer',
      'Brushed-metal directional pattern',
      'Premium decorative effect',
      'Interior feature walls',
      'Applied by certified Cloud Paints teams',
    ],
    specs: {
      'Coverage':   '6–8 m² per litre',
      'Touch dry':  '2 hours',
      'Recoat':     '6 hours',
      'Finish':     'Metallic shimmer',
      'Thinning':   'Ready for use',
      'Application': 'Specialty trowel · Brush',
      'Cleaner':    'Clean water',
    },
    claims: ['Brushed metal, painted on', 'Hotel-grade decorative finish'],
    uses: [
      'Feature walls in luxury lounges',
      'Hotel reception and lobby walls',
      'Showroom and retail accent walls',
      'Restaurant and bar back-bars',
    ],
    surfaces: ['Gypsum board', 'Plaster', 'Previously-painted interiors'],
    application: {
      prep: 'Surface must be silky-smooth — sand, fill and re-sand. Metallic finishes magnify defects.',
      new_surface: 'Prime with tinted Cloud Paints Wall Sealer (closest to final metallic tone).',
      previously_painted: 'Sand sheen off thoroughly. Spot-prime bare patches.',
      method: 'Apply base coat. Apply metallic top coat with specialty trowel in random overlapping arcs to set the directional shimmer.',
      cleanup: 'Wash tools with clean water immediately after use.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based',
      storage: 'Cool, dry place.',
      first_aid: 'Rinse with clean water on contact.',
      disposal: 'Do not empty into drains.',
    },
    datasheet: '',
    pairs_with: ['cloud-venetian-marble', 'cloud-velvet-texture', 'cloud-luxury-stucco'],
  },

  /* 23. CLOUD VENETIAN MARBLE */
  {
    slug: 'cloud-venetian-marble',
    surface_tags: ['gypsum', 'cement'],
    name: 'Cloud Venetian Marble',
    tagline: 'Polished marble plaster',
    cat: 'texture',
    cat_label: 'Venetian Plaster & Marble',
    grade: 'Luxury',
    kebs: '',
    brandClass: 'brand-cloud-venetian',
    primary: '#d4c4a8',
    accent: '#9b8765',
    image: 'images/textures/cloud-venetian-marble.jpg',
    sizes: ['4L', '1L'],
    short: 'A traditional Venetian plaster finish layered and burnished to a high-polish marble look with depth, veining and movement that shifts under light.',
    full: 'Cloud Venetian Marble is a fine-particle lime-style plaster applied in thin layered passes and burnished to a glass-smooth marble finish. Veining and depth appear as the layers build. The premium choice for hotel lobbies, executive offices and master suites that want true craft on the wall.',
    features: [
      'High-polish marble finish',
      'Layered depth with natural veining',
      'Hand-burnished by certified applicators',
      'Light-responsive surface',
      'Hotel and luxury residential grade',
      'Applied in 4–6 thin passes',
    ],
    specs: {
      'Coverage':   '3–4 m² per litre (per pass)',
      'Touch dry':  '2 hours per pass',
      'Recoat':     '4 hours',
      'Finish':     'Polished marble',
      'Thinning':   'Ready for use',
      'Application': 'Trowel · Steel burnish',
      'Cleaner':    'Clean water',
    },
    claims: ['Real Venetian craft, made in Kenya', 'Polished marble, applied not quarried'],
    uses: [
      'Hotel lobbies and reception walls',
      'Master suite feature walls',
      'Executive office statement walls',
      'Luxury residential entryways',
    ],
    surfaces: ['Gypsum board', 'Plaster', 'Pre-skimmed concrete'],
    application: {
      prep: 'Substrate must be silky-smooth and dust-free. Skim if necessary. Prime with tinted Cloud Paints Wall Sealer.',
      new_surface: 'Apply 4–6 thin passes, each thinner than the last. Build colour and depth gradually.',
      previously_painted: 'Strip back to sound substrate. Skim coat recommended.',
      method: 'First passes laid in random arcs to build pattern. Final passes burnished with clean steel trowel to compress and polish. Optional wax for further sheen.',
      cleanup: 'Wash tools with clean water before plaster cures.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based',
      storage: 'Cool, dry place.',
      first_aid: 'Rinse with clean water on contact.',
      disposal: 'Allow residue to cure then dispose as construction waste.',
    },
    datasheet: '',
    pairs_with: ['cloud-luxury-stucco', 'cloud-metallic-illusion', 'silk-vinyl'],
  },

  /* 24. CLOUD RUSTIC TEXTURE */
  {
    slug: 'cloud-rustic-texture',
    surface_tags: ['cement', 'masonry'],
    name: 'Cloud Rustic Texture',
    tagline: 'Earthy hand-rendered finish',
    cat: 'texture',
    cat_label: 'Decorative Pattern',
    grade: 'Decorative',
    kebs: '',
    brandClass: 'brand-cloud-rustic',
    primary: '#9b6b48',
    accent: '#c69372',
    image: 'images/textures/cloud-rustic-texture.jpg',
    sizes: ['20kg', '10kg'],
    short: 'A warm, hand-rendered texture with earthy tones — perfect for restaurants, lounges and any wall that wants a worked-in artisan feel.',
    full: 'Cloud Rustic Texture is a coarse-grain decorative coating laid in irregular hand strokes for a deliberately imperfect, artisan finish. The character comes from the variation — no two walls read the same. Built for restaurants, lounges, boutique hotels and accent walls in residential spaces.',
    features: [
      'Hand-rendered artisan look',
      'Warm earthy tone palette',
      'Hides surface imperfections',
      'Interior and protected exterior use',
      'Tintable to terracotta, ochre, clay',
      'Applied by certified Cloud Paints teams',
    ],
    specs: {
      'Coverage':   '2–3 m² per kg',
      'Touch dry':  '4 hours',
      'Recoat':     '24 hours',
      'Finish':     'Coarse hand-rendered',
      'Thinning':   'Ready for use',
      'Application': 'Trowel · Sponge',
      'Cleaner':    'Clean water',
    },
    claims: ['Artisan walls, made in Kenya', 'The character comes from the variation'],
    uses: [
      'Restaurant and bar accent walls',
      'Boutique hotel corridors',
      'Lounge fireplaces and feature walls',
      'Sheltered courtyard exteriors',
    ],
    surfaces: ['Plaster', 'Masonry', 'Pre-primed exteriors'],
    application: {
      prep: 'Substrate must be sound. Prime with Cloud Paints Wall Sealer.',
      new_surface: 'Allow plaster to cure 14+ days.',
      previously_painted: 'Sand to a key, spot-prime bare patches.',
      method: 'Lay on with trowel in irregular passes. Texture further with sponge, comb or hand brush.',
      cleanup: 'Wash tools with clean water before material cures.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based',
      storage: 'Cool, dry place.',
      first_aid: 'Rinse with clean water on contact.',
      disposal: 'Do not empty into drains.',
    },
    datasheet: '',
    pairs_with: ['cloud-sand-finish', 'cloud-velvet-texture', 'weatherguard'],
  },

  /* 25. CLOUD SAND FINISH */
  {
    slug: 'cloud-sand-finish',
    surface_tags: ['cement', 'gypsum'],
    name: 'Cloud Sand Finish',
    tagline: 'Fine-grain sandstone texture',
    cat: 'texture',
    cat_label: 'Decorative Pattern',
    grade: 'Decorative',
    kebs: '',
    brandClass: 'brand-cloud-sand',
    primary: '#c4a47c',
    accent: '#dbc4a0',
    image: 'images/textures/cloud-sand-finish.jpg',
    sizes: ['20L', '4L'],
    short: 'A fine, sandy textured paint that feels softly granular to the touch — gives walls a subtle natural-stone character without heavy build.',
    full: 'Cloud Sand Finish is a fine-aggregate decorative paint that introduces a soft sandstone texture to interior walls. Lighter build than the stone collection, easier to apply, and ideal where you want texture as a whisper rather than a statement.',
    features: [
      'Fine sand-grain texture',
      'Light-build, easy application',
      'Subtle natural look',
      'Interior accent walls',
      'Tintable to warm earth tones',
      'Applied by certified Cloud Paints teams',
    ],
    specs: {
      'Coverage':   '5–7 m² per litre',
      'Touch dry':  '2 hours',
      'Recoat':     '6 hours',
      'Finish':     'Fine sand grain',
      'Thinning':   'Ready for use',
      'Application': 'Roller · Brush · Spray',
      'Cleaner':    'Clean water',
    },
    claims: ['Texture as a whisper', 'Softly granular'],
    uses: [
      'Bedroom and lounge accent walls',
      'Hallway and corridor walls',
      'Restaurant and café interiors',
      'Boutique retail walls',
    ],
    surfaces: ['Plaster', 'Gypsum board', 'Previously-painted interiors'],
    application: {
      prep: 'Sand smooth and dust off.',
      new_surface: 'Prime with Cloud Paints Wall Sealer.',
      previously_painted: 'Sand sheen off existing paint.',
      method: 'Apply with textured roller in random direction. Two coats recommended.',
      cleanup: 'Wash tools with clean water.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based',
      storage: 'Cool, dry place.',
      first_aid: 'Rinse with clean water on contact.',
      disposal: 'Do not empty into drains.',
    },
    datasheet: '',
    pairs_with: ['cloud-rustic-texture', 'cloud-velvet-texture', 'silk-vinyl'],
  },

  /* 26. CLOUD DESERT STONE */
  {
    slug: 'cloud-desert-stone',
    surface_tags: ['cement', 'masonry'],
    name: 'Cloud Desert Stone',
    tagline: 'Warm Saharan stone texture',
    cat: 'texture',
    cat_label: 'Stone & Exterior Rock',
    grade: 'Decorative',
    kebs: '',
    brandClass: 'brand-cloud-desert',
    primary: '#b58963',
    accent: '#d7b58a',
    image: 'images/textures/cloud-desert-stone.jpg',
    sizes: ['25kg', '20kg'],
    short: 'A warm, Saharan-toned heavy-build stone texture for exterior walls, gate pillars and boundary walls — UV-stable and built for Kenyan dry zones.',
    full: 'Cloud Desert Stone is a heavy-build decorative coating with a warm, sandy stone profile. Hand-trowelled and sculpted to mimic dry-region rock, it offers strong UV stability and weather resistance — well-suited to Kenya\'s drier counties and rift-zone architecture.',
    features: [
      'Warm desert-stone palette',
      'Heavy-build stone profile',
      'High UV stability',
      'Weather and dust resistant',
      'Boundary walls, pillars, façades',
      'Applied by certified Cloud Paints teams',
    ],
    specs: {
      'Coverage':   '2–3 m² per kg',
      'Touch dry':  '4–6 hours',
      'Recoat':     '24 hours',
      'Finish':     'Heavy stone profile',
      'Thinning':   'Ready for use',
      'Application': 'Trowel · Sponge',
      'Cleaner':    'Clean water (wet)',
    },
    claims: ['Built for dry zones', 'Saharan tone, Kenyan durability'],
    uses: [
      'Boundary walls and gate pillars',
      'Rift-zone residential exteriors',
      'Commercial and hospitality façades',
      'Garden and courtyard feature walls',
    ],
    surfaces: ['Plastered masonry', 'Concrete', 'Pre-primed exteriors'],
    application: {
      prep: 'Substrate must be sound, clean and free of laitance.',
      new_surface: 'Cure render 21+ days. Base-coat with Weatherguard.',
      previously_painted: 'Remove flaking material, key the surface.',
      method: 'Trowel apply at 2–3 mm build. Sculpt while wet. Topcoat with Weatherguard tinted to match.',
      cleanup: 'Wash tools with clean water before material cures.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based',
      storage: 'Cool, dry, shaded conditions.',
      first_aid: 'Rinse with clean water on contact.',
      disposal: 'Allow residue to cure then dispose as construction waste.',
    },
    datasheet: '',
    pairs_with: ['cloud-stone-texture', 'weatherguard', 'cloud-rockshield-exterior'],
  },

  /* 27. CLOUD LUXURY STUCCO */
  {
    slug: 'cloud-luxury-stucco',
    surface_tags: ['gypsum', 'cement'],
    name: 'Cloud Luxury Stucco',
    tagline: 'Polished plaster luxury finish',
    cat: 'texture',
    cat_label: 'Venetian Plaster & Marble',
    grade: 'Luxury',
    kebs: '',
    brandClass: 'brand-cloud-stucco',
    primary: '#ddc9b5',
    accent: '#b09b85',
    image: 'images/textures/cloud-luxury-stucco.jpg',
    sizes: ['4L', '1L'],
    short: 'A premium polished-plaster finish with soft cloud-like depth — sister to the Venetian Marble but with a gentler, more contemporary feel.',
    full: 'Cloud Luxury Stucco is a polished plaster from the same Venetian family, but laid in broader, softer passes for a contemporary cloud-like depth instead of crisp marble veining. Used in master suites, executive offices and any interior that wants quiet luxury without grand drama.',
    features: [
      'Polished plaster finish',
      'Soft cloud-depth passes',
      'Hand-burnished by certified applicators',
      'Light-responsive surface',
      'Luxury residential and executive',
      'Applied in 3–5 thin passes',
    ],
    specs: {
      'Coverage':   '3–4 m² per litre (per pass)',
      'Touch dry':  '2 hours per pass',
      'Recoat':     '4 hours',
      'Finish':     'Polished plaster',
      'Thinning':   'Ready for use',
      'Application': 'Trowel · Steel burnish',
      'Cleaner':    'Clean water',
    },
    claims: ['Quietly luxurious', 'Cloud-depth, hand-burnished'],
    uses: [
      'Luxury master bedroom walls',
      'Executive office accent walls',
      'Hotel suite interiors',
      'High-end residential entryways',
    ],
    surfaces: ['Gypsum board', 'Plaster', 'Pre-skimmed concrete'],
    application: {
      prep: 'Substrate must be silky-smooth and dust-free.',
      new_surface: 'Apply 3–5 thin passes.',
      previously_painted: 'Strip back to sound substrate. Skim coat recommended.',
      method: 'Lay passes in broad overlapping arcs. Burnish final pass with clean steel trowel.',
      cleanup: 'Wash tools with clean water before plaster cures.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based',
      storage: 'Cool, dry place.',
      first_aid: 'Rinse with clean water on contact.',
      disposal: 'Allow residue to cure then dispose as construction waste.',
    },
    datasheet: '',
    pairs_with: ['cloud-venetian-marble', 'cloud-metallic-illusion', 'silk-vinyl'],
  },

  /* 28. CLOUD ROCKSHIELD EXTERIOR TEXTURE */
  {
    slug: 'cloud-rockshield-exterior',
    surface_tags: ['cement', 'masonry'],
    name: 'Cloud RockShield Exterior Texture',
    tagline: 'Heavy-duty exterior shield + finish',
    cat: 'texture',
    cat_label: 'Stone & Exterior Rock',
    grade: 'Premium',
    kebs: '',
    brandClass: 'brand-cloud-rockshield',
    primary: '#5e605e',
    accent: '#8b8f8b',
    image: 'images/textures/cloud-rockshield-exterior.jpg',
    sizes: ['25kg', '20kg'],
    short: 'A heavy-duty, weather-shielded exterior texture engineered for commercial buildings and high-exposure walls — the strongest member of the Cloud Texture Collection.',
    full: 'Cloud RockShield Exterior Texture pairs the Cloud Texture Collection\'s decorative range with a reinforced weather-shield system. Built for commercial façades, high-rise exposed walls and high-rainfall regions, it combines a sculpted stone profile with the Dual Protection Technology that anchors Cloud Paints\' Weatherguard exterior system.',
    features: [
      'Heavy-duty weather shield',
      'Sculpted stone profile',
      'Dual Protection Technology base',
      'Engineered for commercial scale',
      'UV, rain and dust resistant',
      'Applied by certified Cloud Paints teams',
    ],
    specs: {
      'Coverage':   '2–3 m² per kg',
      'Touch dry':  '4–6 hours',
      'Recoat':     '24 hours',
      'Finish':     'Heavy stone with shield coat',
      'Thinning':   'Ready for use',
      'Application': 'Trowel · Steel float',
      'Cleaner':    'Clean water (wet)',
    },
    claims: ['Decorative + protective in one system', 'Built for commercial scale'],
    uses: [
      'Commercial building façades',
      'High-rise exposed walls',
      'Coastal and high-rainfall exteriors',
      'Hospitality and institutional exteriors',
    ],
    surfaces: ['Plastered masonry', 'Concrete', 'Pre-primed exteriors'],
    application: {
      prep: 'Substrate must be sound, clean and dry.',
      new_surface: 'Cure render 21+ days. Apply Weatherguard primer.',
      previously_painted: 'Remove flaking material, pressure-wash, key the surface.',
      method: 'Trowel-build texture in two passes. Topcoat with Weatherguard Dual Protection.',
      cleanup: 'Wash tools with clean water before material cures.',
    },
    safety: {
      lead: 'Lead-free formulation',
      voc: 'Low VOC · water-based',
      storage: 'Cool, dry, shaded conditions.',
      first_aid: 'Rinse with clean water on contact.',
      disposal: 'Allow residue to cure then dispose as construction waste.',
    },
    datasheet: '',
    pairs_with: ['weatherguard', 'cloud-stone-texture', 'cloud-desert-stone'],
  },

];

// Helper for finding a product by slug
window.getProduct = function (slug) {
  return window.CLOUD_PRODUCTS.find(function (p) { return p.slug === slug; });
};
