// ============================================================
// CLOUD PAINTS — Projects catalogue
// ============================================================
// Editorial metadata for every project showcased on the
// Projects page. Referenced by js/projects-page.js.
// ============================================================

window.CLOUD_PROJECTS = [
  {
    slug: 'pazuri-vipingo',
    name: 'Pazuri Vipingo',
    location: 'Kilifi',
    county: 'Kilifi',
    year: '2025',
    type: 'residential',
    type_label: 'Coastal Villas',
    client: 'Superior Homes',
    scope: 'Supply only',
    brief: 'A cluster of beachfront holiday villas fifteen minutes north of Kilifi town. The brief called for a coastal palette that could hold its own against salt spray, humidity and the equatorial sun — bright whites and warm earths sealed with our Weatherguard exterior system.',
    products_used: ['weatherguard', 'vinyl-matt'],
    image: 'images/projects/pazuri-vipingo.jpg',
    accent: '#c07551',
    featured: true,
  },
  {
    slug: 'pazuri-villa',
    name: 'Pazuri Villa',
    location: 'Kilifi',
    county: 'Kilifi',
    year: '2025',
    type: 'residential',
    type_label: 'Villa',
    client: 'Private',
    scope: 'Supply only',
    brief: 'A single family villa within the Pazuri development painted in a crisp white Weatherguard finish to bounce heat and keep the interiors cool.',
    products_used: ['weatherguard'],
    image: 'images/projects/pazuri-villa.jpg',
    accent: '#efe6d2',
  },
  {
    slug: 'emana-apartments',
    name: 'Emana Apartments',
    location: 'Nairobi',
    county: 'Nairobi',
    year: '2024',
    type: 'residential',
    type_label: 'Apartments',
    client: 'Private developer',
    scope: 'Supply only',
    brief: 'A twenty-four unit apartment block finished in a warm two-tone scheme — mustard body with charcoal banding — executed in Weatherguard for the exterior and Vinyl Matt for the circulation areas.',
    products_used: ['weatherguard', 'vinyl-matt', 'supermatt'],
    image: 'images/projects/emana-apartments.jpg',
    accent: '#b8934a',
  },
  {
    slug: 'westpointe-madaraka',
    name: 'Westpointe · Madaraka',
    location: 'Madaraka, Nairobi',
    county: 'Nairobi',
    year: '2024',
    type: 'residential',
    type_label: '256 units',
    client: 'Shady Acres',
    scope: 'Supply & Finish',
    brief: 'A flagship job opposite Strathmore University — 256 apartments finished top to bottom by the Cloud Paints trade team. Interiors in Silk Vinyl, circulation in SuperMatt, exteriors sealed with Weatherguard. Delivered on a tight handover schedule across eight blocks.',
    products_used: ['silk-vinyl', 'supermatt', 'weatherguard', 'vinyl-matt'],
    image: 'images/projects/westpointe-stairwell.jpg',
    accent: '#5a4374',
    featured: true,
  },
  {
    slug: 'westpointe-corridors',
    name: 'Westpointe Flats',
    location: 'Madaraka, Nairobi',
    county: 'Nairobi',
    year: '2024',
    type: 'residential',
    type_label: 'Corridors',
    client: 'Shady Acres',
    scope: 'Supply & Finish',
    brief: 'Companion block to the main Westpointe scheme — corridors and common areas in a hard-wearing SuperMatt base with Vinyl Matt accent walls.',
    products_used: ['supermatt', 'vinyl-matt'],
    image: 'images/projects/westpointe-corridors.jpg',
    accent: '#efe6d2',
  },
  {
    slug: 'complex-plaza',
    name: 'Complex Plaza 2',
    location: 'Nairobi',
    county: 'Nairobi',
    year: '2024',
    type: 'commercial',
    type_label: 'Commercial',
    client: 'Private developer',
    scope: 'Supply only',
    brief: 'A five-storey commercial block finished in a deep mustard Weatherguard exterior — a colour choice that reads warm against the Nairobi sky and doesn\'t show dust in the way lighter shades do.',
    products_used: ['weatherguard'],
    image: 'images/projects/complex-plaza.jpg',
    accent: '#e8a317',
  },
  {
    slug: 'vanice-estate',
    name: 'Vanice Estate · Acacia',
    location: 'Kitengela',
    county: 'Kajiado',
    year: '2024',
    type: 'residential',
    type_label: 'Estate',
    client: 'Acacia Crest',
    scope: 'Supply only',
    brief: 'Forty townhouses in the Acacia Estate, Kitengela. Two body colours alternating across the terrace — Savanna gold and a softer bone — both finished in Weatherguard with Rocketex texture on plinth courses.',
    products_used: ['weatherguard', 'rocketex', 'vinyl-matt'],
    image: 'images/projects/vanice-estate.jpg',
    accent: '#e8a317',
  },
  {
    slug: 'amana-apartments',
    name: 'Amana Apartments',
    location: 'Kitengela',
    county: 'Kajiado',
    year: '2023',
    type: 'residential',
    type_label: 'Apartments',
    client: 'Private developer',
    scope: 'Supply & Finish',
    brief: 'A Kitengela apartment block finished by the Cloud Paints team using Wallmaster Rocketex on the exterior to hide masonry variation, with Weatherguard as the colour coat. Interiors in Iris economy emulsion for a budget-sensitive, hard-wearing finish.',
    products_used: ['rocketex', 'weatherguard', 'iris-economy'],
    image: 'images/projects/amana-apartments.jpg',
    accent: '#166534',
    featured: true,
  },
  {
    slug: 'mlolongo-commercial',
    name: 'Mlolongo Flat',
    location: 'Mlolongo',
    county: 'Machakos',
    year: '2023',
    type: 'commercial',
    type_label: 'Commercial',
    client: 'Private',
    scope: 'Supply only',
    brief: 'Mixed-use retail-above-residential block on the Mombasa road, exterior entirely in Weatherguard. A high-dust, high-traffic corridor — Weatherguard\'s anti-carbonation formula was specified for longevity.',
    products_used: ['weatherguard'],
    image: 'images/projects/mlolongo-commercial.jpg',
    accent: '#8b1e2c',
  },
  {
    slug: 'residential-syokimau',
    name: 'Residential · Syokimau',
    location: 'Syokimau',
    county: 'Machakos',
    year: '2023',
    type: 'residential',
    type_label: 'Residential',
    client: 'Private',
    scope: 'Supply only',
    brief: 'Five-bedroom standalone home in Syokimau finished with Wallmaster Rocketex on the exterior and a bespoke warm-grey Vinyl Matt across the interior volumes.',
    products_used: ['rocketex', 'vinyl-matt'],
    image: 'images/projects/residential-syokimau.jpg',
    accent: '#1e3a8a',
  },
  {
    slug: 'moi-forces',
    name: 'Moi Forces Academy',
    location: 'Nairobi',
    county: 'Nairobi',
    year: '2023',
    type: 'hospitality',
    type_label: 'Institutional',
    client: 'Moi Forces Academy',
    scope: 'Supply & Finish',
    brief: 'New science laboratory block at Moi Forces Academy. Chemistry-resistant surfaces demanded our Gloss Enamel for the bench frames and doors, with SuperMatt + Silk Vinyl walls throughout the teaching areas.',
    products_used: ['gloss-enamel', 'silk-vinyl', 'supermatt'],
    image: 'images/projects/moi-forces.jpg',
    accent: '#1e3a8a',
  },
];

window.getProject = function (slug) {
  return window.CLOUD_PROJECTS.find(function (p) { return p.slug === slug; });
};
