// ============================================================
// CLOUD PAINTS — Projects catalogue
// ============================================================
// Editorial metadata for every project showcased on the
// Projects page. Referenced by js/projects-page.js.
// ============================================================

window.CLOUD_PROJECTS = [
  {
    slug: 'pazuri-vipingo',
    inspiration: 'images/inspiration/inspiration-coastal-villa-lamu.jpg',
    name: 'Pazuri Vipingo',
    location: 'Kilifi',
    county: 'Kilifi',
    year: '2025',
    type: 'residential',
    type_label: 'Coastal Villas',
    brief: 'A cluster of beachfront holiday villas fifteen minutes north of Kilifi town. The brief called for a coastal palette that could hold its own against salt spray, humidity and the equatorial sun — bright whites and warm earths sealed with our Weatherguard exterior system.',
    products_used: ['weatherguard', 'vinyl-matt'],
    image: 'images/projects/pazuri-vipingo.jpg',
    accent: '#c07551',
    featured: true,
  },
  {
    slug: 'pazuri-villa',
    inspiration: 'images/inspiration/inspiration-coastal-veranda.jpg',
    name: 'Pazuri Villa',
    location: 'Kilifi',
    county: 'Kilifi',
    year: '2025',
    type: 'residential',
    type_label: 'Villa',
    brief: 'A single family villa within the Pazuri development painted in a crisp white Weatherguard finish to bounce heat and keep the interiors cool.',
    products_used: ['weatherguard'],
    image: 'images/projects/pazuri-villa.jpg',
    accent: '#efe6d2',
  },
  {
    slug: 'lukenya-plains',
    inspiration: 'images/inspiration/inspiration-buruburu-maisonette.jpg',
    name: 'Lukenya Plains',
    location: 'Athi River',
    county: 'Machakos',
    year: '2024',
    type: 'residential',
    type_label: 'Homes',
    brief: 'A Superior Homes residential development on the Lukenya plains. Exteriors finished in a warm, dust-tolerant Weatherguard palette chosen to sit comfortably against the open savanna light.',
    products_used: ['weatherguard', 'vinyl-matt'],
    image: 'images/projects/new-project-1.jpg',
    accent: '#c4870a',
  },
  {
    slug: 'superior-greenpark',
    inspiration: 'images/inspiration/inspiration-apartment-urban-tower.jpg',
    name: 'Superior Homes Head Office · Green Park',
    location: 'Athi River',
    county: 'Machakos',
    year: '2024',
    type: 'commercial',
    type_label: 'Head Office',
    brief: 'The Superior Homes head office at the Green Park development. A crisp corporate finish — Weatherguard on the exterior elevations with Silk Vinyl through the interior office volumes.',
    products_used: ['weatherguard', 'silk-vinyl', 'supermatt'],
    image: 'images/projects/new-project-2.jpg',
    accent: '#166534',
  },
  {
    slug: 'emana-apartments',
    inspiration: 'images/inspiration/inspiration-apartments-sage.jpg',
    name: 'Emana Apartments',
    location: 'Kitengela',
    county: 'Kajiado',
    year: '2024',
    type: 'residential',
    type_label: 'Apartments',
    brief: 'A twenty-four unit apartment block finished in a warm two-tone scheme — mustard body with charcoal banding — executed in Weatherguard for the exterior and Vinyl Matt for the circulation areas.',
    products_used: ['weatherguard', 'vinyl-matt', 'supermatt'],
    // The bare block before any coating went on. Paired with `image` below
    // it carries the before/after on the project card and modal.
    image_before: 'images/projects/mlolongo-commercial.jpg',
    image: 'images/projects/emana-apartments.jpg',
    accent: '#b8934a',
  },
  {
    slug: 'westpointe-madaraka',
    inspiration: 'images/inspiration/inspiration-apartments-sage.jpg',
    name: 'Westpointe · Madaraka',
    location: 'Madaraka, Nairobi',
    county: 'Nairobi',
    year: '2024',
    type: 'residential',
    type_label: '256 units',
    brief: 'A flagship job opposite Strathmore University — 256 apartments finished top to bottom by the Cloud Paints trade team. Interiors in Silk Vinyl, circulation in SuperMatt, exteriors sealed with Weatherguard. Delivered on a tight handover schedule across eight blocks.',
    products_used: ['silk-vinyl', 'supermatt', 'weatherguard', 'vinyl-matt'],
    image: 'images/projects/westpointe-stairwell.jpg',
    accent: '#5a4374',
    featured: true,
  },
  {
    slug: 'westpointe-corridors',
    inspiration: 'images/inspiration/inspiration-rust-hallway.jpg',
    name: 'Westpointe Flats',
    location: 'Madaraka, Nairobi',
    county: 'Nairobi',
    year: '2024',
    type: 'residential',
    type_label: 'Corridors',
    brief: 'Companion block to the main Westpointe scheme — corridors and common areas in a hard-wearing SuperMatt base with Vinyl Matt accent walls.',
    products_used: ['supermatt', 'vinyl-matt'],
    image: 'images/projects/westpointe-corridors.jpg',
    accent: '#efe6d2',
  },
  {
    slug: 'complex-plaza',
    inspiration: 'images/inspiration/inspiration-apartment-urban-tower.jpg',
    name: 'Complex Plaza 2',
    location: 'Nairobi',
    county: 'Nairobi',
    year: '2024',
    type: 'commercial',
    type_label: 'Commercial',
    brief: 'A five-storey commercial block finished in a deep mustard Weatherguard exterior — a colour choice that reads warm against the Nairobi sky and doesn\'t show dust in the way lighter shades do.',
    products_used: ['weatherguard'],
    image: 'images/projects/complex-plaza.jpg',
    accent: '#e8a317',
  },
  {
    slug: 'vanice-estate',
    inspiration: 'images/inspiration/inspiration-savanna-living.jpg',
    name: 'Vanice Estate · Acacia',
    location: 'Kitengela',
    county: 'Kajiado',
    year: '2024',
    type: 'residential',
    type_label: 'Estate',
    brief: 'Forty townhouses in the Acacia Estate, Kitengela. Two body colours alternating across the terrace — Savanna gold and a softer bone — both finished in Weatherguard with Rocketex texture on plinth courses.',
    products_used: ['weatherguard', 'rocketex', 'vinyl-matt'],
    image: 'images/projects/vanice-estate.jpg',
    accent: '#e8a317',
  },
  {
    slug: 'amana-apartments',
    inspiration: 'images/inspiration/inspiration-apartments-sage.jpg',
    name: 'Amana Apartments',
    location: 'Kitengela',
    county: 'Kajiado',
    year: '2023',
    type: 'residential',
    type_label: 'Apartments',
    brief: 'A Kitengela apartment block finished by the Cloud Paints team using Wallmaster Rocketex on the exterior to hide masonry variation, with Weatherguard as the colour coat. Interiors in Iris economy emulsion for a budget-sensitive, hard-wearing finish.',
    products_used: ['rocketex', 'weatherguard', 'iris-economy'],
    image: 'images/projects/amana-apartments.jpg',
    accent: '#166534',
    featured: true,
  },
  {
    slug: 'residential-syokimau',
    inspiration: 'images/inspiration/inspiration-villa-cream-charcoal.jpg',
    name: 'Residential · Syokimau',
    location: 'Syokimau',
    county: 'Machakos',
    year: '2023',
    type: 'residential',
    type_label: 'Residential',
    brief: 'Five-bedroom standalone home in Syokimau finished with Wallmaster Rocketex on the exterior and a bespoke warm-grey Vinyl Matt across the interior volumes.',
    products_used: ['rocketex', 'vinyl-matt'],
    image: 'images/projects/residential-syokimau.jpg',
    accent: '#1e3a8a',
  },
  {
    // De-identified: the project stays in the portfolio, the institution's
    // name does not.
    slug: 'science-laboratory-block',
    inspiration: 'images/inspiration/inspiration-warm-white-kitchen.jpg',
    name: 'Science Laboratory Block',
    location: 'Nairobi',
    county: 'Nairobi',
    year: '2023',
    type: 'hospitality',
    type_label: 'Institutional',
    brief: 'A new science laboratory block in Nairobi. Chemistry-resistant surfaces demanded our Gloss Enamel for the bench frames and doors, with SuperMatt and Silk Vinyl walls throughout the teaching areas.',
    products_used: ['gloss-enamel', 'silk-vinyl', 'supermatt'],
    image: 'images/projects/moi-forces.jpg',
    accent: '#1e3a8a',
  },
];

window.getProject = function (slug) {
  return window.CLOUD_PROJECTS.find(function (p) { return p.slug === slug; });
};

// ============================================================
// SHOWCASE — purely visual imagery (no name, no click target).
// Powers the auto-panning hero ribbon and the "Wall of work"
// gallery. Use for extra project shots and AI-generated visuals
// where attribution doesn't apply.
// ============================================================
window.CLOUD_SHOWCASE = [
  { image: 'images/projects/new-project-3.jpg', accent: '#c4870a' },
  { image: 'images/projects/new-project-4.jpg', accent: '#1f4088' },
  { image: 'images/projects/new-project-5.jpg', accent: '#166534' },
  { image: 'images/projects/green-roof-villa.jpg',           accent: '#2f5d40' },
  { image: 'images/projects/cloud-red-roof-residence.jpg',   accent: '#b25a44' },
  { image: 'images/projects/cloud-apartments-terracotta.jpg', accent: '#a83a1c' },
];
